import type { Destination, Package } from './types';

/**
 * Sample content — used two ways:
 *  1. `npm run seed` loads it into Supabase as a starting catalogue.
 *  2. When Supabase env vars are missing (fresh deploy), the public site
 *     renders this directly so the site is never empty.
 */

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?q=80&w=${w}&auto=format&fit=crop`;

export const sampleDestinations: Destination[] = [
  {
    id: 1, slug: 'maldives', name: 'Maldives', region: 'Indian Ocean',
    blurb: 'Overwater villas, house reefs and sunsets that stop time. Paradise, made easy from the UAE.',
    heroImage: img('photo-1514282401047-d79a71a590e8'), featured: true, sortOrder: 1,
  },
  {
    id: 2, slug: 'georgia', name: 'Georgia', region: 'Caucasus',
    blurb: 'Ancient monasteries, mountain silhouettes and legendary hospitality — a short flight, a world away.',
    heroImage: img('photo-1565008576549-57569a49371d'), featured: true, sortOrder: 2,
  },
  {
    id: 3, slug: 'japan', name: 'Japan', region: 'Asia & Far East',
    blurb: 'Unique culture, stunning scenery. Temples and bullet trains, ryokans and neon nights.',
    heroImage: img('photo-1493976040374-85c8e12f0c0e'), featured: true, sortOrder: 3,
  },
  {
    id: 4, slug: 'switzerland', name: 'Switzerland', region: 'Europe',
    blurb: 'Explore the heart of the Alps — glacier peaks, lake towns and the world’s most scenic railways.',
    heroImage: img('photo-1530122037265-a5f1f91d3b99'), featured: true, sortOrder: 4,
  },
  {
    id: 5, slug: 'thailand', name: 'Thailand', region: 'Asia & Far East',
    blurb: 'Pristine beaches, exceptional value. Island-hop the Andaman Sea and eat like royalty.',
    heroImage: img('photo-1552465011-b4e21bf6e79a'), featured: true, sortOrder: 5,
  },
  {
    id: 6, slug: 'jordan', name: 'Jordan', region: 'Middle East',
    blurb: 'Ancient wonders, modern discoveries. Petra at dawn, Wadi Rum by starlight, the Dead Sea in between.',
    heroImage: img('photo-1548786811-dd6e453ccca7'), featured: true, sortOrder: 6,
  },
  {
    id: 7, slug: 'united-arab-emirates', name: 'United Arab Emirates', region: 'Middle East',
    blurb: 'Special offers on the UAE’s finest hotels — desert resorts, beach clubs and skyline suites.',
    heroImage: img('photo-1512453979798-5ea266f8880c'), featured: true, sortOrder: 7,
  },
];

export const samplePackages: Package[] = [
  {
    id: 1,
    slug: 'hard-rock-hotel-maldives',
    title: 'Hard Rock Hotel Maldives',
    tagline: 'Beachfront rhythm on Crossroads Maldives — music, lagoon life and serious style.',
    destinationSlug: 'maldives', destinationName: 'Maldives', region: 'Indian Ocean',
    category: 'Beach & Islands', nights: 4, days: 5,
    priceFrom: 6780, currency: 'AED',
    heroImage: img('photo-1586500036706-41963de24d8b'),
    gallery: [img('photo-1586500036706-41963de24d8b', 1200), img('photo-1573843981267-be1999ff37cd', 1200), img('photo-1544550581-5f7ceaf7f992', 1200)],
    overview: [
      'Set on the Crossroads lifestyle marina just fifteen minutes from Malé by speedboat, Hard Rock Hotel Maldives pairs the islands’ turquoise calm with a beat you can actually feel. Overwater villas and beach pool villas come with the brand’s signature swagger — think in-room Fender guitars, a world-class spa and the biggest kids’ club in the atoll.',
      'Your package includes daily breakfast at Sessions, return speedboat transfers and full access to the Marina @ Crossroads promenade — a dozen restaurants, boutiques and a beach club without ever needing another boat.',
    ],
    highlights: [
      'Overwater and beachfront villas with private pools',
      '15-minute speedboat transfer — no seaplane needed',
      'Marina @ Crossroads: 12+ restaurants and a beach club on your doorstep',
      'Rock Spa®, Body Rock® gym and Roxity Kids Club®',
      'House reef snorkelling and complimentary non-motorised water sports',
    ],
    includes: [
      '4 nights in a Silver Beach Studio (upgrades available)',
      'Daily international breakfast at Sessions',
      'Return speedboat transfers from Velana International Airport',
      'All taxes, green tax and service charges',
      'Complimentary Wi-Fi and non-motorised water sports',
      'Dedicated PCT concierge before and during travel',
    ],
    excludes: ['International flights (we’ll quote you the best fare)', 'Travel insurance', 'Lunches, dinners and premium beverages', 'Excursions and motorised water sports'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival in paradise', description: 'Meet & greet at Velana International Airport and a 15-minute speedboat ride to Crossroads. Check in, sunset drinks on the marina.' },
      { label: 'Day 2', title: 'Lagoon life', description: 'Breakfast at Sessions, then a day of house-reef snorkelling, kayaking and pool time. Evening live music at the Hard Rock stage.' },
      { label: 'Day 3', title: 'Island hopping', description: 'Optional excursions: sandbank picnic, dolphin cruise or a dive on the outer reef. Rock Spa treatment to finish.' },
      { label: 'Day 4', title: 'Marina day', description: 'Explore the Marina @ Crossroads — beach club, boutiques and dinner at your pick of a dozen restaurants.' },
      { label: 'Day 5', title: 'Departure', description: 'Slow breakfast, late checkout on request, speedboat back to Malé for your flight home.' },
    ],
    hotelName: 'Hard Rock Hotel Maldives', boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 2,
    slug: 'varu-by-atmosphere-maldives',
    title: 'Varu by Atmosphere — All Inclusive',
    tagline: 'A five-star island where everything — dining, drinks, excursions — is already taken care of.',
    destinationSlug: 'maldives', destinationName: 'Maldives', region: 'Indian Ocean',
    category: 'Beach & Islands', nights: 4, days: 5,
    priceFrom: 9270, currency: 'AED',
    heroImage: img('photo-1544550581-5f7ceaf7f992'),
    gallery: [img('photo-1544550581-5f7ceaf7f992', 1200), img('photo-1590523741831-ab7e8b8f9c7f', 1200), img('photo-1602002418816-5c0aeef426aa', 1200)],
    overview: [
      'Varu by Atmosphere is the Maldives with the brakes off: a genuine premium all-inclusive where sunset fishing trips, snorkelling safaris, fine wines and even a spa credit are part of the plan. Forty minutes from Malé by speedboat, the island sits on a vivid house reef with resident turtles and reef sharks.',
      'Choose a beach villa wrapped in tropical garden or go full postcard with a water villa on stilts over the lagoon. Either way, the Varu Plan™ means you sign nothing all week.',
    ],
    highlights: [
      'True premium all-inclusive — the Varu Plan™',
      'Weekly sunset cruise, fishing trip and guided snorkel safari included',
      'Vibrant house reef with turtles metres from your villa',
      'Three restaurants including overwater teppanyaki',
      'Spa credit and daily replenished minibar',
    ],
    includes: [
      '4 nights in a Beach Villa (Water Villa upgrade available)',
      'All meals at Lime & Chilli plus themed dinners',
      'Premium branded drinks, cocktails and wines',
      'Return speedboat transfers',
      'Weekly excursions: sunset cruise, fishing, snorkel safari',
      'US$100 spa credit per stay',
      'All taxes and service charges',
    ],
    excludes: ['International flights (ask us for a bundled fare)', 'Travel insurance', 'Private excursions and diving courses'],
    itinerary: [
      { label: 'Day 1', title: 'Welcome to Varu', description: 'Speedboat transfer from Malé, welcome drinks, villa check-in and your first sunset over the lagoon.' },
      { label: 'Day 2', title: 'House reef day', description: 'Guided snorkel safari on the house reef — turtles, rays and technicolour coral. Teppanyaki dinner overwater.' },
      { label: 'Day 3', title: 'Out on the water', description: 'Morning dolphin cruise, lazy afternoon by the infinity pool, traditional Maldivian night market dinner.' },
      { label: 'Day 4', title: 'Spa & sunset', description: 'Use your spa credit at ELE|NA, then join the sunset fishing trip — the chef grills your catch.' },
      { label: 'Day 5', title: 'Departure', description: 'Final reef swim, breakfast, and the speedboat back to Malé.' },
    ],
    hotelName: 'Varu by Atmosphere', boardBasis: 'Premium All Inclusive',
    featured: true, status: 'published',
  },
  {
    id: 3,
    slug: 'georgia-discovery',
    title: 'Grand Georgia Discovery',
    tagline: 'Ten days through the Caucasus — Tbilisi, wine country, mountain passes and the Black Sea.',
    destinationSlug: 'georgia', destinationName: 'Georgia', region: 'Caucasus',
    category: 'Culture & Heritage', nights: 9, days: 10,
    priceFrom: 4570, currency: 'AED',
    heroImage: img('photo-1565008576549-57569a49371d'),
    gallery: [img('photo-1565008576549-57569a49371d', 1200), img('photo-1504198458649-3128b932f49e', 1200), img('photo-1571939228382-b2f2b585ce15', 1200)],
    overview: [
      'Georgia rewards the curious like nowhere else within four hours of the Gulf. This ten-day journey links cobbled Tbilisi, the cave city of Uplistsikhe, Kazbegi’s mountain church above the clouds and the vineyards of Kakheti — where wine was invented eight thousand years ago.',
      'Travel is by private air-conditioned vehicle with an English-speaking guide, staying in a hand-picked mix of boutique city hotels and mountain lodges. Expect supra feasts, toasts with strangers and scenery that fills a camera roll.',
    ],
    highlights: [
      'Old Tbilisi walking tour, sulphur baths and Narikala fortress',
      'Gergeti Trinity Church beneath Mount Kazbek',
      'Wine tasting and supra feast in Kakheti',
      'Cave city of Uplistsikhe and UNESCO-listed Mtskheta',
      'Private guide and driver throughout',
    ],
    includes: [
      '9 nights in 4★ boutique hotels and lodges',
      'Daily breakfast plus 4 traditional dinners with wine',
      'Private transport with English-speaking guide',
      'All entrance fees on the itinerary',
      'Airport transfers',
      'PCT 24/7 in-trip support line',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches and personal expenses', 'Gratuities'],
    itinerary: [
      { label: 'Days 1–3', title: 'Tbilisi', description: 'Old town lanes, the Bridge of Peace, sulphur baths and dinner in a courtyard restaurant. Day trip to Mtskheta, Georgia’s ancient capital.' },
      { label: 'Days 4–5', title: 'Kazbegi', description: 'North along the Georgian Military Highway past Ananuri fortress. 4x4 up to Gergeti Trinity Church; overnight facing Mount Kazbek.' },
      { label: 'Days 6–7', title: 'Kakheti wine country', description: 'Qvevri cellars, family wineries and a proper supra feast in Sighnaghi, the "city of love" overlooking the Alazani Valley.' },
      { label: 'Days 8–9', title: 'Gori & Uplistsikhe', description: 'The cave city carved into rock 3,000 years ago, then back to Tbilisi for last-night wine bars and shopping.' },
      { label: 'Day 10', title: 'Departure', description: 'Transfer to Tbilisi airport with a bottle of saperavi in your suitcase.' },
    ],
    hotelName: null, boardBasis: 'Breakfast + 4 dinners',
    featured: true, status: 'published',
  },
  {
    id: 4,
    slug: 'tbilisi-city-break',
    title: 'Tbilisi City Break',
    tagline: 'Five days of old-town wandering, sulphur baths and mountain day trips — remarkable value.',
    destinationSlug: 'georgia', destinationName: 'Georgia', region: 'Caucasus',
    category: 'City Breaks', nights: 4, days: 5,
    priceFrom: 3340, currency: 'AED',
    heroImage: img('photo-1571939228382-b2f2b585ce15'),
    gallery: [img('photo-1571939228382-b2f2b585ce15', 1200), img('photo-1565008576549-57569a49371d', 1200)],
    overview: [
      'The perfect long weekend: direct flights, no visa fuss for UAE residents, and a capital that mixes crumbling art-nouveau balconies with natural wine bars and cable cars. This break bundles a central 4★ hotel with guided days to Mtskheta and the Kazbegi mountains, leaving you free time to get happily lost.',
    ],
    highlights: [
      'Central 4★ hotel in walking distance of the old town',
      'Guided Tbilisi city tour with cable car and fortress',
      'Full-day Kazbegi mountain excursion',
      'Half-day Mtskheta and Jvari monastery trip',
      'Traditional dinner with folklore show',
    ],
    includes: [
      '4 nights bed & breakfast in a 4★ hotel',
      'Airport transfers and all excursion transport',
      'English-speaking guide on tour days',
      'One traditional dinner with wine',
      'All entrance fees',
    ],
    excludes: ['International flights', 'Travel insurance', 'Meals not listed'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival', description: 'Transfer to your hotel, evening stroll along Rustaveli Avenue.' },
      { label: 'Day 2', title: 'Tbilisi tour', description: 'Old town, Narikala fortress by cable car, sulphur bath district and the flea market.' },
      { label: 'Day 3', title: 'Kazbegi day trip', description: 'The Georgian Military Highway to Gergeti Trinity Church — one of the great mountain views.' },
      { label: 'Day 4', title: 'Mtskheta & free time', description: 'Morning at UNESCO-listed Mtskheta; free afternoon. Farewell dinner with folklore show.' },
      { label: 'Day 5', title: 'Departure', description: 'Free morning and airport transfer.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: false, status: 'published',
  },
  {
    id: 5,
    slug: 'japan-golden-route',
    title: 'Japan Golden Route',
    tagline: 'Tokyo, Hakone and Kyoto by bullet train — the essential first taste of Japan.',
    destinationSlug: 'japan', destinationName: 'Japan', region: 'Asia & Far East',
    category: 'Culture & Heritage', nights: 7, days: 8,
    priceFrom: 12900, currency: 'AED',
    heroImage: img('photo-1493976040374-85c8e12f0c0e'),
    gallery: [img('photo-1493976040374-85c8e12f0c0e', 1200), img('photo-1526481280693-3bfa7568e0f3', 1200), img('photo-1528360983277-13d401cdc186', 1200)],
    overview: [
      'Neon Tokyo, steaming onsen towns and temple-quiet Kyoto, stitched together by the shinkansen. This eight-day route is the classic for good reason — it delivers the full sweep of Japan on one seamless rail line, with hand-picked hotels and a night in a traditional ryokan with kaiseki dinner.',
      'We include a 7-day Japan Rail Pass, airport transfers and a private guided day in each city, with the rest of your time free to explore with our detailed digital travel companion.',
    ],
    highlights: [
      'Bullet train travel with 7-day JR Pass included',
      'Ryokan night in Hakone with onsen and kaiseki dinner',
      'Private guided days in Tokyo and Kyoto',
      'Fushimi Inari’s ten thousand torii gates',
      'Mount Fuji views from Lake Ashi (weather permitting)',
    ],
    includes: [
      '7 nights: 4★ hotels in Tokyo & Kyoto + ryokan in Hakone',
      'Daily breakfast and one kaiseki dinner',
      '7-day ordinary Japan Rail Pass',
      'Private English-speaking guide (2 full days)',
      'Airport transfers by shared limousine bus',
      'PCT digital itinerary with maps, phrases and bookings',
    ],
    excludes: ['International flights', 'Travel insurance', 'Most lunches and dinners', 'Temple entrance fees on free days'],
    itinerary: [
      { label: 'Days 1–3', title: 'Tokyo', description: 'Shibuya crossing, Senso-ji at dawn, teamLab, izakaya alleys — with one full day privately guided.' },
      { label: 'Day 4', title: 'Hakone', description: 'Shinkansen to the mountains. Lake Ashi cruise, ropeway over the sulphur valley, then your ryokan’s onsen and kaiseki feast.' },
      { label: 'Days 5–7', title: 'Kyoto', description: 'Fushimi Inari, Kinkaku-ji’s golden pavilion, Arashiyama bamboo grove and a geisha-district evening walk.' },
      { label: 'Day 8', title: 'Departure', description: 'Express train to Kansai or back to Tokyo for your flight.' },
    ],
    hotelName: null, boardBasis: 'Breakfast + 1 kaiseki dinner',
    featured: true, status: 'published',
  },
  {
    id: 6,
    slug: 'swiss-alps-escape',
    title: 'Swiss Alps Escape',
    tagline: 'Lucerne, Interlaken and Zermatt — lakes, peaks and the world’s most beautiful train rides.',
    destinationSlug: 'switzerland', destinationName: 'Switzerland', region: 'Europe',
    category: 'Adventure', nights: 5, days: 6,
    priceFrom: 8400, currency: 'AED',
    heroImage: img('photo-1530122037265-a5f1f91d3b99'),
    gallery: [img('photo-1530122037265-a5f1f91d3b99', 1200), img('photo-1527004013197-933c4bb611b3', 1200)],
    overview: [
      'Switzerland in one graceful arc: lakeside Lucerne, adventure-capital Interlaken and car-free Zermatt under the Matterhorn. A Swiss Travel Pass covers every train, boat and bus — including the panoramic GoldenPass and Gotthard lines — so the journey is the holiday.',
    ],
    highlights: [
      'Swiss Travel Pass — unlimited trains, boats and buses',
      'Gornergrat railway with Matterhorn panorama',
      'Lake Lucerne paddle-steamer cruise',
      'Optional Jungfraujoch "Top of Europe" excursion',
      'Car-free Zermatt village stay',
    ],
    includes: [
      '5 nights in 4★ hotels with breakfast',
      '2nd-class Swiss Travel Pass for 6 days',
      'Gornergrat cogwheel railway ticket',
      'Lake Lucerne cruise',
      'PCT rail-day planner with seat-side views mapped',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches and dinners', 'Jungfraujoch supplement'],
    itinerary: [
      { label: 'Day 1', title: 'Zurich → Lucerne', description: 'Arrive Zurich, scenic train to Lucerne. Chapel Bridge and old-town evening.' },
      { label: 'Day 2', title: 'Lake Lucerne', description: 'Paddle-steamer cruise and Mount Pilatus golden round trip.' },
      { label: 'Day 3', title: 'Interlaken', description: 'GoldenPass panoramic line through the Brünig Pass; afternoon between the two lakes.' },
      { label: 'Day 4', title: 'Jungfrau region', description: 'Optional Jungfraujoch excursion or Grindelwald hikes and cliff walk.' },
      { label: 'Day 5', title: 'Zermatt', description: 'Train up the Matter Valley. Gornergrat railway for the Matterhorn in full glory.' },
      { label: 'Day 6', title: 'Departure', description: 'Glacier-view breakfast, then rail connection to Zurich or Geneva airport.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: false, status: 'published',
  },
  {
    id: 7,
    slug: 'thailand-island-hopping',
    title: 'Thailand Island Hopping',
    tagline: 'Phuket, Phi Phi and Krabi — seven days of longtail boats, limestone bays and beach bars.',
    destinationSlug: 'thailand', destinationName: 'Thailand', region: 'Asia & Far East',
    category: 'Beach & Islands', nights: 6, days: 7,
    priceFrom: 5900, currency: 'AED',
    heroImage: img('photo-1552465011-b4e21bf6e79a'),
    gallery: [img('photo-1552465011-b4e21bf6e79a', 1200), img('photo-1537956965359-7573183d1f57', 1200), img('photo-1528181304800-259b08848526', 1200)],
    overview: [
      'The Andaman Sea’s greatest hits at a price that makes the Maldives jealous. Start in Phuket’s old town, ferry to Phi Phi’s impossible lagoons, and finish beneath Krabi’s limestone karsts at Railay Beach — with speedboat day trips, beachfront resorts and exceptional Thai food throughout.',
    ],
    highlights: [
      'Maya Bay and Pileh Lagoon by early-bird speedboat',
      'Railay Beach and the four-island Krabi tour',
      'Phuket old town food walk',
      'Beachfront 4★ resorts on every island',
      'All ferries and transfers arranged door-to-door',
    ],
    includes: [
      '6 nights in 4★ beachfront resorts',
      'Daily breakfast',
      'All ferries, speedboats and private land transfers',
      'Phi Phi early-bird tour with lunch',
      'Krabi four-island longtail tour with lunch',
      'PCT 24/7 in-trip support line',
    ],
    excludes: ['International flights', 'Travel insurance', 'National park fees (paid locally)', 'Dinners'],
    itinerary: [
      { label: 'Days 1–2', title: 'Phuket', description: 'Beach time on Kata or Bang Tao, sunset at the Big Buddha and an old-town street-food walk.' },
      { label: 'Days 3–4', title: 'Phi Phi Islands', description: 'Ferry across, then the early-bird speedboat to Maya Bay before the crowds. Snorkel Pileh Lagoon and Bamboo Island.' },
      { label: 'Days 5–6', title: 'Krabi & Railay', description: 'Longtail to Railay’s limestone amphitheatre, four-island tour, fire-show beach bars.' },
      { label: 'Day 7', title: 'Departure', description: 'Transfer to Krabi or Phuket airport.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 8,
    slug: 'jordan-ancient-wonders',
    title: 'Jordan: Ancient Wonders',
    tagline: 'Petra, Wadi Rum and the Dead Sea in one unforgettable five-day sweep.',
    destinationSlug: 'jordan', destinationName: 'Jordan', region: 'Middle East',
    category: 'Culture & Heritage', nights: 4, days: 5,
    priceFrom: 6200, currency: 'AED',
    heroImage: img('photo-1548786811-dd6e453ccca7'),
    gallery: [img('photo-1548786811-dd6e453ccca7', 1200), img('photo-1547234935-80c7145ec969', 1200)],
    overview: [
      'Three of Earth’s great experiences sit within three hours’ drive of each other in Jordan: the rose-red city of Petra, the Mars-scape of Wadi Rum and the impossible float of the Dead Sea. This compact itinerary covers all three with a private driver-guide, a night under Bedouin canvas and a Dead Sea spa resort finale.',
    ],
    highlights: [
      'Petra by day — the Siq, Treasury and Monastery climb',
      'Wadi Rum 4x4 desert safari and Bedouin camp overnight',
      'Dead Sea float and mud ritual at a 5★ spa resort',
      'Private driver-guide throughout',
      'Amman citadel and downtown souk',
    ],
    includes: [
      '4 nights: Amman, Petra, Wadi Rum camp, Dead Sea resort',
      'Daily breakfast and 2 dinners (camp + resort)',
      'Private car with English-speaking driver-guide',
      'Petra and Wadi Rum entrance fees',
      'Jordan Pass visa waiver assistance',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches', 'Petra by Night ticket'],
    itinerary: [
      { label: 'Day 1', title: 'Amman', description: 'Arrival, citadel viewpoint, Roman theatre and dinner downtown.' },
      { label: 'Day 2', title: 'Petra', description: 'The King’s Highway south via Madaba’s mosaics. Afternoon first look at the Siq and Treasury.' },
      { label: 'Day 3', title: 'Petra → Wadi Rum', description: 'Early Monastery climb, then into the desert: 4x4 dunes, sunset from the rocks, dinner and stargazing at camp.' },
      { label: 'Day 4', title: 'Dead Sea', description: 'Drive to the lowest point on Earth. Float, mud, spa, infinity-pool sunset.' },
      { label: 'Day 5', title: 'Departure', description: 'Lazy morning at the resort, transfer to Amman airport.' },
    ],
    hotelName: null, boardBasis: 'Breakfast + 2 dinners',
    featured: false, status: 'published',
  },
  {
    id: 9,
    slug: 'uae-luxury-staycation',
    title: 'UAE Luxury Staycation',
    tagline: 'Weekend reset at the Emirates’ finest beach and desert resorts — resident rates, PCT perks.',
    destinationSlug: 'united-arab-emirates', destinationName: 'United Arab Emirates', region: 'Middle East',
    category: 'Staycations', nights: 2, days: 3,
    priceFrom: 1450, currency: 'AED',
    heroImage: img('photo-1512453979798-5ea266f8880c'),
    gallery: [img('photo-1512453979798-5ea266f8880c', 1200), img('photo-1518684079-3c830dcef090', 1200)],
    overview: [
      'No airport required. We hold preferred rates at the UAE’s standout resorts — Saadiyat Island beach houses, Ras Al Khaimah cliffside retreats, Palm Jumeirah icons and desert camps under Fujairah’s mountains — usually with breakfast, late checkout and a resort credit thrown in.',
      'Tell us the vibe (beach, desert, mountains or skyline) and we’ll send three tailored options within a day.',
    ],
    highlights: [
      'Hand-picked 5★ resorts across all seven emirates',
      'PCT perks: late checkout, resort credit, room upgrades where available',
      'Beach, desert, mountain and city options',
      'Instant confirmation on most dates',
    ],
    includes: [
      '2 nights at your chosen 5★ resort',
      'Daily breakfast for two',
      'Resort credit or perk where available',
      'PCT concierge for dining and spa bookings',
    ],
    excludes: ['Transport to the resort', 'Tourism dirham fee (paid at checkout)', 'Lunches and dinners'],
    itinerary: [
      { label: 'Day 1', title: 'Check in & unwind', description: 'Early check-in where available. Beach, pool and sunset drinks.' },
      { label: 'Day 2', title: 'Full resort day', description: 'Spa morning, beach afternoon, dinner reservation made by your concierge.' },
      { label: 'Day 3', title: 'Slow departure', description: 'Late checkout, long breakfast, home by dinner.' },
    ],
    hotelName: 'Your choice of partner resorts', boardBasis: 'Bed & Breakfast',
    featured: false, status: 'published',
  },
];

export const sampleTestimonials = [
  {
    quote: 'Every detail was handled — transfers, dinners, even a birthday cake in the villa. The best travel company we have used in the UAE.',
    name: 'Sarah & James M.', trip: 'Varu by Atmosphere, Maldives',
  },
  {
    quote: 'Our Georgia tour felt private and personal. The guide became a friend and the itinerary was paced perfectly.',
    name: 'The Al Rashid family', trip: 'Grand Georgia Discovery',
  },
  {
    quote: 'From first enquiry to the quote PDF to the trip itself — professional at every step. Japan was flawless.',
    name: 'Daniel K.', trip: 'Japan Golden Route',
  },
];

export const SERVICES = [
  { title: 'Tailor-made packages', text: 'Flights, hotels and experiences shaped around you — not off a shelf.' },
  { title: 'Cruises', text: 'Local Arabian Gulf sailings and international itineraries with the major lines.' },
  { title: 'Staycations', text: 'Preferred rates at the UAE’s finest resorts, often with extras included.' },
  { title: 'Travel insurance', text: 'Comprehensive cover arranged in minutes alongside your booking.' },
  { title: 'Car hire', text: 'Self-drive and chauffeur options at your destination, ready on arrival.' },
  { title: 'Airport lounges', text: 'Lounge access worldwide to start the holiday before boarding.' },
];
