import type { Package } from './types';

/**
 * Sample content — used two ways:
 *  1. `npm run seed` loads it into Supabase as a starting catalogue.
 *  2. When Supabase env vars are missing (fresh deploy), the public site
 *     renders this directly so the site is never empty.
 */

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?q=80&w=${w}&auto=format&fit=crop`;

export { DESTINATION_CATALOGUE as sampleDestinations } from './destination-catalogue';


export const samplePackages: Package[] = [
  {
    id: 1,
    slug: 'hard-rock-hotel-maldives',
    title: 'Hard Rock Hotel Maldives',
    tagline: 'Beachfront rhythm on Crossroads Maldives — music, lagoon life and serious style.',
    destinationSlug: 'maldives', destinationName: 'Maldives', region: 'Indian Ocean',
    brand: 'holidays', category: 'Beach & Islands', nights: 4, days: 5,
    priceFrom: 6780, currency: 'AED',
    heroImage: img('photo-1586500036706-41963de24d8b'),
    gallery: [img('photo-1586500036706-41963de24d8b', 1200), img('photo-1573843981267-be1999ff37cd', 1200), img('photo-1544550581-5f7ceaf7f992', 1200)],
    overview: [
      'Set on the Crossroads lifestyle marina just fifteen minutes from Malé by speedboat, Hard Rock Hotel Maldives pairs the islands’ turquoise calm with a beat you can actually feel. Overwater villas and beach pool villas come with the brand’s signature swagger — think in-room Fender guitars, a world-class spa and the biggest kids’ club in the atoll.',
      'Your package includes daily breakfast at Sessions, return speedboat transfers and full access to the Marina @ Crossroads promenade — a dozen restaurants, boutiques and a beach club without ever needing another boat.',
    ],
    highlights: [
      'Overwater and beachfront villas with private pools',
      '15-minute speedboat transfer — no seaplane needed',
      'Marina @ Crossroads: 12+ restaurants and a beach club on your doorstep',
      'Rock Spa®, Body Rock® gym and Roxity Kids Club®',
      'House reef snorkelling and complimentary non-motorised water sports',
    ],
    includes: [
      '4 nights in a Silver Beach Studio (upgrades available)',
      'Daily international breakfast at Sessions',
      'Return speedboat transfers from Velana International Airport',
      'All taxes, green tax and service charges',
      'Complimentary Wi-Fi and non-motorised water sports',
      'Dedicated PCT concierge before and during travel',
    ],
    excludes: ['International flights (we’ll quote you the best fare)', 'Travel insurance', 'Lunches, dinners and premium beverages', 'Excursions and motorised water sports'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival in paradise', description: 'Meet & greet at Velana International Airport and a 15-minute speedboat ride to Crossroads. Check in, sunset drinks on the marina.' },
      { label: 'Day 2', title: 'Lagoon life', description: 'Breakfast at Sessions, then a day of house-reef snorkelling, kayaking and pool time. Evening live music at the Hard Rock stage.' },
      { label: 'Day 3', title: 'Island hopping', description: 'Optional excursions: sandbank picnic, dolphin cruise or a dive on the outer reef. Rock Spa treatment to finish.' },
      { label: 'Day 4', title: 'Marina day', description: 'Explore the Marina @ Crossroads — beach club, boutiques and dinner at your pick of a dozen restaurants.' },
      { label: 'Day 5', title: 'Departure', description: 'Slow breakfast, late checkout on request, speedboat back to Malé for your flight home.' },
    ],
    hotelName: 'Hard Rock Hotel Maldives', boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 2,
    slug: 'varu-by-atmosphere-maldives',
    title: 'Varu by Atmosphere — All Inclusive',
    tagline: 'A five-star island where everything — dining, drinks, excursions — is already taken care of.',
    destinationSlug: 'maldives', destinationName: 'Maldives', region: 'Indian Ocean',
    brand: 'holidays', category: 'Beach & Islands', nights: 4, days: 5,
    priceFrom: 9270, currency: 'AED',
    heroImage: img('photo-1544550581-5f7ceaf7f992'),
    gallery: [img('photo-1544550581-5f7ceaf7f992', 1200), img('photo-1590523741831-ab7e8b8f9c7f', 1200), img('photo-1602002418816-5c0aeef426aa', 1200)],
    overview: [
      'Varu by Atmosphere is the Maldives with the brakes off: a genuine premium all-inclusive where sunset fishing trips, snorkelling safaris, fine wines and even a spa credit are part of the plan. Forty minutes from Malé by speedboat, the island sits on a vivid house reef with resident turtles and reef sharks.',
      'Choose a beach villa wrapped in tropical garden or go full postcard with a water villa on stilts over the lagoon. Either way, the Varu Plan™ means you sign nothing all week.',
    ],
    highlights: [
      'True premium all-inclusive — the Varu Plan™',
      'Weekly sunset cruise, fishing trip and guided snorkel safari included',
      'Vibrant house reef with turtles metres from your villa',
      'Three restaurants including overwater teppanyaki',
      'Spa credit and daily replenished minibar',
    ],
    includes: [
      '4 nights in a Beach Villa (Water Villa upgrade available)',
      'All meals at Lime & Chilli plus themed dinners',
      'Premium branded drinks, cocktails and wines',
      'Return speedboat transfers',
      'Weekly excursions: sunset cruise, fishing, snorkel safari',
      'US$100 spa credit per stay',
      'All taxes and service charges',
    ],
    excludes: ['International flights (ask us for a bundled fare)', 'Travel insurance', 'Private excursions and diving courses'],
    itinerary: [
      { label: 'Day 1', title: 'Welcome to Varu', description: 'Speedboat transfer from Malé, welcome drinks, villa check-in and your first sunset over the lagoon.' },
      { label: 'Day 2', title: 'House reef day', description: 'Guided snorkel safari on the house reef — turtles, rays and technicolour coral. Teppanyaki dinner overwater.' },
      { label: 'Day 3', title: 'Out on the water', description: 'Morning dolphin cruise, lazy afternoon by the infinity pool, traditional Maldivian night market dinner.' },
      { label: 'Day 4', title: 'Spa & sunset', description: 'Use your spa credit at ELE|NA, then join the sunset fishing trip — the chef grills your catch.' },
      { label: 'Day 5', title: 'Departure', description: 'Final reef swim, breakfast, and the speedboat back to Malé.' },
    ],
    hotelName: 'Varu by Atmosphere', boardBasis: 'Premium All Inclusive',
    featured: true, status: 'published',
  },
  {
    id: 3,
    slug: 'georgia-discovery',
    title: 'Grand Georgia Discovery',
    tagline: 'Ten days through the Caucasus — Tbilisi, wine country, mountain passes and the Black Sea.',
    destinationSlug: 'georgia', destinationName: 'Georgia', region: 'Caucasus',
    brand: 'holidays', category: 'Culture & Heritage', nights: 9, days: 10,
    priceFrom: 4570, currency: 'AED',
    heroImage: img('photo-1565008576549-57569a49371d'),
    gallery: [img('photo-1565008576549-57569a49371d', 1200), img('photo-1504198458649-3128b932f49e', 1200), img('photo-1571939228382-b2f2b585ce15', 1200)],
    overview: [
      'Georgia rewards the curious like nowhere else within four hours of the Gulf. This ten-day journey links cobbled Tbilisi, the cave city of Uplistsikhe, Kazbegi’s mountain church above the clouds and the vineyards of Kakheti — where wine was invented eight thousand years ago.',
      'Travel is by private air-conditioned vehicle with an English-speaking guide, staying in a hand-picked mix of boutique city hotels and mountain lodges. Expect supra feasts, toasts with strangers and scenery that fills a camera roll.',
    ],
    highlights: [
      'Old Tbilisi walking tour, sulphur baths and Narikala fortress',
      'Gergeti Trinity Church beneath Mount Kazbek',
      'Wine tasting and supra feast in Kakheti',
      'Cave city of Uplistsikhe and UNESCO-listed Mtskheta',
      'Private guide and driver throughout',
    ],
    includes: [
      '9 nights in 4★ boutique hotels and lodges',
      'Daily breakfast plus 4 traditional dinners with wine',
      'Private transport with English-speaking guide',
      'All entrance fees on the itinerary',
      'Airport transfers',
      'PCT 24/7 in-trip support line',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches and personal expenses', 'Gratuities'],
    itinerary: [
      { label: 'Days 1–3', title: 'Tbilisi', description: 'Old town lanes, the Bridge of Peace, sulphur baths and dinner in a courtyard restaurant. Day trip to Mtskheta, Georgia’s ancient capital.' },
      { label: 'Days 4–5', title: 'Kazbegi', description: 'North along the Georgian Military Highway past Ananuri fortress. 4x4 up to Gergeti Trinity Church; overnight facing Mount Kazbek.' },
      { label: 'Days 6–7', title: 'Kakheti wine country', description: 'Qvevri cellars, family wineries and a proper supra feast in Sighnaghi, the "city of love" overlooking the Alazani Valley.' },
      { label: 'Days 8–9', title: 'Gori & Uplistsikhe', description: 'The cave city carved into rock 3,000 years ago, then back to Tbilisi for last-night wine bars and shopping.' },
      { label: 'Day 10', title: 'Departure', description: 'Transfer to Tbilisi airport with a bottle of saperavi in your suitcase.' },
    ],
    hotelName: null, boardBasis: 'Breakfast + 4 dinners',
    featured: true, status: 'published',
  },
  {
    id: 4,
    slug: 'tbilisi-city-break',
    title: 'Tbilisi City Break',
    tagline: 'Five days of old-town wandering, sulphur baths and mountain day trips — remarkable value.',
    destinationSlug: 'georgia', destinationName: 'Georgia', region: 'Caucasus',
    brand: 'holidays', category: 'City Breaks', nights: 4, days: 5,
    priceFrom: 3340, currency: 'AED',
    heroImage: img('photo-1571939228382-b2f2b585ce15'),
    gallery: [img('photo-1571939228382-b2f2b585ce15', 1200), img('photo-1565008576549-57569a49371d', 1200)],
    overview: [
      'The perfect long weekend: direct flights, no visa fuss for UAE residents, and a capital that mixes crumbling art-nouveau balconies with natural wine bars and cable cars. This break bundles a central 4★ hotel with guided days to Mtskheta and the Kazbegi mountains, leaving you free time to get happily lost.',
    ],
    highlights: [
      'Central 4★ hotel in walking distance of the old town',
      'Guided Tbilisi city tour with cable car and fortress',
      'Full-day Kazbegi mountain excursion',
      'Half-day Mtskheta and Jvari monastery trip',
      'Traditional dinner with folklore show',
    ],
    includes: [
      '4 nights bed & breakfast in a 4★ hotel',
      'Airport transfers and all excursion transport',
      'English-speaking guide on tour days',
      'One traditional dinner with wine',
      'All entrance fees',
    ],
    excludes: ['International flights', 'Travel insurance', 'Meals not listed'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival', description: 'Transfer to your hotel, evening stroll along Rustaveli Avenue.' },
      { label: 'Day 2', title: 'Tbilisi tour', description: 'Old town, Narikala fortress by cable car, sulphur bath district and the flea market.' },
      { label: 'Day 3', title: 'Kazbegi day trip', description: 'The Georgian Military Highway to Gergeti Trinity Church — one of the great mountain views.' },
      { label: 'Day 4', title: 'Mtskheta & free time', description: 'Morning at UNESCO-listed Mtskheta; free afternoon. Farewell dinner with folklore show.' },
      { label: 'Day 5', title: 'Departure', description: 'Free morning and airport transfer.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: false, status: 'published',
  },
  {
    id: 5,
    slug: 'japan-golden-route',
    title: 'Japan Golden Route',
    tagline: 'Tokyo, Hakone and Kyoto by bullet train — the essential first taste of Japan.',
    destinationSlug: 'japan', destinationName: 'Japan', region: 'Asia & Far East',
    brand: 'holidays', category: 'Culture & Heritage', nights: 7, days: 8,
    priceFrom: 12900, currency: 'AED',
    heroImage: img('photo-1493976040374-85c8e12f0c0e'),
    gallery: [img('photo-1493976040374-85c8e12f0c0e', 1200), img('photo-1526481280693-3bfa7568e0f3', 1200), img('photo-1528360983277-13d401cdc186', 1200)],
    overview: [
      'Neon Tokyo, steaming onsen towns and temple-quiet Kyoto, stitched together by the shinkansen. This eight-day route is the classic for good reason — it delivers the full sweep of Japan on one seamless rail line, with hand-picked hotels and a night in a traditional ryokan with kaiseki dinner.',
      'We include a 7-day Japan Rail Pass, airport transfers and a private guided day in each city, with the rest of your time free to explore with our detailed digital travel companion.',
    ],
    highlights: [
      'Bullet train travel with 7-day JR Pass included',
      'Ryokan night in Hakone with onsen and kaiseki dinner',
      'Private guided days in Tokyo and Kyoto',
      'Fushimi Inari’s ten thousand torii gates',
      'Mount Fuji views from Lake Ashi (weather permitting)',
    ],
    includes: [
      '7 nights: 4★ hotels in Tokyo & Kyoto + ryokan in Hakone',
      'Daily breakfast and one kaiseki dinner',
      '7-day ordinary Japan Rail Pass',
      'Private English-speaking guide (2 full days)',
      'Airport transfers by shared limousine bus',
      'PCT digital itinerary with maps, phrases and bookings',
    ],
    excludes: ['International flights', 'Travel insurance', 'Most lunches and dinners', 'Temple entrance fees on free days'],
    itinerary: [
      { label: 'Days 1–3', title: 'Tokyo', description: 'Shibuya crossing, Senso-ji at dawn, teamLab, izakaya alleys — with one full day privately guided.' },
      { label: 'Day 4', title: 'Hakone', description: 'Shinkansen to the mountains. Lake Ashi cruise, ropeway over the sulphur valley, then your ryokan’s onsen and kaiseki feast.' },
      { label: 'Days 5–7', title: 'Kyoto', description: 'Fushimi Inari, Kinkaku-ji’s golden pavilion, Arashiyama bamboo grove and a geisha-district evening walk.' },
      { label: 'Day 8', title: 'Departure', description: 'Express train to Kansai or back to Tokyo for your flight.' },
    ],
    hotelName: null, boardBasis: 'Breakfast + 1 kaiseki dinner',
    featured: true, status: 'published',
  },
  {
    id: 6,
    slug: 'swiss-alps-escape',
    title: 'Swiss Alps Escape',
    tagline: 'Lucerne, Interlaken and Zermatt — lakes, peaks and the world’s most beautiful train rides.',
    destinationSlug: 'switzerland', destinationName: 'Switzerland', region: 'Europe',
    brand: 'holidays', category: 'Adventure', nights: 5, days: 6,
    priceFrom: 8400, currency: 'AED',
    heroImage: img('photo-1530122037265-a5f1f91d3b99'),
    gallery: [img('photo-1530122037265-a5f1f91d3b99', 1200), img('photo-1527004013197-933c4bb611b3', 1200)],
    overview: [
      'Switzerland in one graceful arc: lakeside Lucerne, adventure-capital Interlaken and car-free Zermatt under the Matterhorn. A Swiss Travel Pass covers every train, boat and bus — including the panoramic GoldenPass and Gotthard lines — so the journey is the holiday.',
    ],
    highlights: [
      'Swiss Travel Pass — unlimited trains, boats and buses',
      'Gornergrat railway with Matterhorn panorama',
      'Lake Lucerne paddle-steamer cruise',
      'Optional Jungfraujoch "Top of Europe" excursion',
      'Car-free Zermatt village stay',
    ],
    includes: [
      '5 nights in 4★ hotels with breakfast',
      '2nd-class Swiss Travel Pass for 6 days',
      'Gornergrat cogwheel railway ticket',
      'Lake Lucerne cruise',
      'PCT rail-day planner with seat-side views mapped',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches and dinners', 'Jungfraujoch supplement'],
    itinerary: [
      { label: 'Day 1', title: 'Zurich → Lucerne', description: 'Arrive Zurich, scenic train to Lucerne. Chapel Bridge and old-town evening.' },
      { label: 'Day 2', title: 'Lake Lucerne', description: 'Paddle-steamer cruise and Mount Pilatus golden round trip.' },
      { label: 'Day 3', title: 'Interlaken', description: 'GoldenPass panoramic line through the Brünig Pass; afternoon between the two lakes.' },
      { label: 'Day 4', title: 'Jungfrau region', description: 'Optional Jungfraujoch excursion or Grindelwald hikes and cliff walk.' },
      { label: 'Day 5', title: 'Zermatt', description: 'Train up the Matter Valley. Gornergrat railway for the Matterhorn in full glory.' },
      { label: 'Day 6', title: 'Departure', description: 'Glacier-view breakfast, then rail connection to Zurich or Geneva airport.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: false, status: 'published',
  },
  {
    id: 7,
    slug: 'thailand-island-hopping',
    title: 'Thailand Island Hopping',
    tagline: 'Phuket, Phi Phi and Krabi — seven days of longtail boats, limestone bays and beach bars.',
    destinationSlug: 'thailand', destinationName: 'Thailand', region: 'Asia & Far East',
    brand: 'holidays', category: 'Beach & Islands', nights: 6, days: 7,
    priceFrom: 5900, currency: 'AED',
    heroImage: img('photo-1552465011-b4e21bf6e79a'),
    gallery: [img('photo-1552465011-b4e21bf6e79a', 1200), img('photo-1537956965359-7573183d1f57', 1200), img('photo-1528181304800-259b08848526', 1200)],
    overview: [
      'The Andaman Sea’s greatest hits at a price that makes the Maldives jealous. Start in Phuket’s old town, ferry to Phi Phi’s impossible lagoons, and finish beneath Krabi’s limestone karsts at Railay Beach — with speedboat day trips, beachfront resorts and exceptional Thai food throughout.',
    ],
    highlights: [
      'Maya Bay and Pileh Lagoon by early-bird speedboat',
      'Railay Beach and the four-island Krabi tour',
      'Phuket old town food walk',
      'Beachfront 4★ resorts on every island',
      'All ferries and transfers arranged door-to-door',
    ],
    includes: [
      '6 nights in 4★ beachfront resorts',
      'Daily breakfast',
      'All ferries, speedboats and private land transfers',
      'Phi Phi early-bird tour with lunch',
      'Krabi four-island longtail tour with lunch',
      'PCT 24/7 in-trip support line',
    ],
    excludes: ['International flights', 'Travel insurance', 'National park fees (paid locally)', 'Dinners'],
    itinerary: [
      { label: 'Days 1–2', title: 'Phuket', description: 'Beach time on Kata or Bang Tao, sunset at the Big Buddha and an old-town street-food walk.' },
      { label: 'Days 3–4', title: 'Phi Phi Islands', description: 'Ferry across, then the early-bird speedboat to Maya Bay before the crowds. Snorkel Pileh Lagoon and Bamboo Island.' },
      { label: 'Days 5–6', title: 'Krabi & Railay', description: 'Longtail to Railay’s limestone amphitheatre, four-island tour, fire-show beach bars.' },
      { label: 'Day 7', title: 'Departure', description: 'Transfer to Krabi or Phuket airport.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 8,
    slug: 'jordan-ancient-wonders',
    title: 'Jordan: Ancient Wonders',
    tagline: 'Petra, Wadi Rum and the Dead Sea in one unforgettable five-day sweep.',
    destinationSlug: 'jordan', destinationName: 'Jordan', region: 'Middle East',
    brand: 'holidays', category: 'Culture & Heritage', nights: 4, days: 5,
    priceFrom: 6200, currency: 'AED',
    heroImage: img('photo-1548786811-dd6e453ccca7'),
    gallery: [img('photo-1548786811-dd6e453ccca7', 1200), img('photo-1547234935-80c7145ec969', 1200)],
    overview: [
      'Three of Earth’s great experiences sit within three hours’ drive of each other in Jordan: the rose-red city of Petra, the Mars-scape of Wadi Rum and the impossible float of the Dead Sea. This compact itinerary covers all three with a private driver-guide, a night under Bedouin canvas and a Dead Sea spa resort finale.',
    ],
    highlights: [
      'Petra by day — the Siq, Treasury and Monastery climb',
      'Wadi Rum 4x4 desert safari and Bedouin camp overnight',
      'Dead Sea float and mud ritual at a 5★ spa resort',
      'Private driver-guide throughout',
      'Amman citadel and downtown souk',
    ],
    includes: [
      '4 nights: Amman, Petra, Wadi Rum camp, Dead Sea resort',
      'Daily breakfast and 2 dinners (camp + resort)',
      'Private car with English-speaking driver-guide',
      'Petra and Wadi Rum entrance fees',
      'Jordan Pass visa waiver assistance',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches', 'Petra by Night ticket'],
    itinerary: [
      { label: 'Day 1', title: 'Amman', description: 'Arrival, citadel viewpoint, Roman theatre and dinner downtown.' },
      { label: 'Day 2', title: 'Petra', description: 'The King’s Highway south via Madaba’s mosaics. Afternoon first look at the Siq and Treasury.' },
      { label: 'Day 3', title: 'Petra → Wadi Rum', description: 'Early Monastery climb, then into the desert: 4x4 dunes, sunset from the rocks, dinner and stargazing at camp.' },
      { label: 'Day 4', title: 'Dead Sea', description: 'Drive to the lowest point on Earth. Float, mud, spa, infinity-pool sunset.' },
      { label: 'Day 5', title: 'Departure', description: 'Lazy morning at the resort, transfer to Amman airport.' },
    ],
    hotelName: null, boardBasis: 'Breakfast + 2 dinners',
    featured: false, status: 'published',
  },
  {
    id: 9,
    slug: 'uae-luxury-staycation',
    title: 'UAE Luxury Staycation',
    tagline: 'Weekend reset at the Emirates’ finest beach and desert resorts — resident rates, PCT perks.',
    destinationSlug: 'united-arab-emirates', destinationName: 'United Arab Emirates', region: 'Middle East',
    brand: 'staycations', category: 'Staycations', nights: 2, days: 3,
    priceFrom: 1450, currency: 'AED',
    heroImage: img('photo-1512453979798-5ea266f8880c'),
    gallery: [img('photo-1512453979798-5ea266f8880c', 1200), img('photo-1518684079-3c830dcef090', 1200)],
    overview: [
      'No airport required. We hold preferred rates at the UAE’s standout resorts — Saadiyat Island beach houses, Ras Al Khaimah cliffside retreats, Palm Jumeirah icons and desert camps under Fujairah’s mountains — usually with breakfast, late checkout and a resort credit thrown in.',
      'Tell us the vibe (beach, desert, mountains or skyline) and we’ll send three tailored options within a day.',
    ],
    highlights: [
      'Hand-picked 5★ resorts across all seven emirates',
      'PCT perks: late checkout, resort credit, room upgrades where available',
      'Beach, desert, mountain and city options',
      'Instant confirmation on most dates',
    ],
    includes: [
      '2 nights at your chosen 5★ resort',
      'Daily breakfast for two',
      'Resort credit or perk where available',
      'PCT concierge for dining and spa bookings',
    ],
    excludes: ['Transport to the resort', 'Tourism dirham fee (paid at checkout)', 'Lunches and dinners'],
    itinerary: [
      { label: 'Day 1', title: 'Check in & unwind', description: 'Early check-in where available. Beach, pool and sunset drinks.' },
      { label: 'Day 2', title: 'Full resort day', description: 'Spa morning, beach afternoon, dinner reservation made by your concierge.' },
      { label: 'Day 3', title: 'Slow departure', description: 'Late checkout, long breakfast, home by dinner.' },
    ],
    hotelName: 'Your choice of partner resorts', boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },

  /* ───────────────────────────── Golf Holidays ───────────────────────────── */
  {
    id: 10,
    slug: 'scotland-links-classic',
    title: 'Scotland Links Classic',
    tagline: 'Five days on the coast that invented golf — Fife links, firm fairways and whisky nightcaps.',
    destinationSlug: 'scotland', destinationName: 'Scotland', region: 'Europe',
    brand: 'golf', category: 'Adventure', nights: 4, days: 5,
    priceFrom: 9800, currency: 'AED',
    heroImage: img('photo-1672871582992-1b30b19878f5'),
    gallery: [img('photo-1672871582992-1b30b19878f5', 1200)],
    overview: [
      'The pilgrimage every golfer owes themselves: four nights in the Kingdom of Fife with three confirmed links rounds, sea views from the tee and a clubhouse dram waiting at the end of each day. We arrange tee times, club hire and transfers — you bring the swing.',
    ],
    highlights: [
      'Three confirmed links rounds with guaranteed tee times',
      'Stay in the heart of the historic golf coast',
      'St Andrews town — the home of golf — on your doorstep',
      'Private transfers between hotel and courses',
      'Whisky-tasting evening arranged on request',
    ],
    includes: [
      '4 nights bed & breakfast in a 4★ golf hotel',
      '3 rounds of links golf, tee times confirmed in advance',
      'Return airport transfers and course transport',
      'PCT golf concierge for pairings and extras',
    ],
    excludes: ['International flights', 'Travel insurance', 'Club hire and caddies', 'Lunches and dinners'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival in Fife', description: 'Transfer from Edinburgh, check in, range session and an early night — you tee off in the morning.' },
      { label: 'Days 2–4', title: 'Three links rounds', description: 'A round a day on classic Fife links, afternoons free for St Andrews, coastal walks or a fourth cheeky nine.' },
      { label: 'Day 5', title: 'Departure', description: 'Full Scottish breakfast, transfer to Edinburgh for your flight home.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 11,
    slug: 'algarve-golf-escape',
    title: 'Algarve Golf Escape',
    tagline: 'Winter sun, clifftop courses and long Portuguese lunches between rounds.',
    destinationSlug: 'portugal', destinationName: 'Portugal', region: 'Europe',
    brand: 'golf', category: 'Beach & Islands', nights: 4, days: 5,
    priceFrom: 5400, currency: 'AED',
    heroImage: img('photo-1562760156-9353a70352ef'),
    gallery: [img('photo-1562760156-9353a70352ef', 1200)],
    overview: [
      'Europe’s most dependable golf weather, courses that tumble along Atlantic cliffs, and resorts that take the game as seriously as you do. This escape pairs a golf-front resort stay with three rounds across the Algarve’s best-loved layouts — buggies included.',
    ],
    highlights: [
      'Three rounds on top-ranked Algarve courses, buggy included',
      'Golf-front 4★ resort with pool and spa',
      '300+ days of sunshine — reliable golf year-round',
      'Non-golfer friendly: beaches and old-town Faro nearby',
    ],
    includes: [
      '4 nights bed & breakfast in a golf resort',
      '3 rounds including shared buggy',
      'Return airport transfers',
      'Pre-booked tee times at your preferred pace',
    ],
    excludes: ['International flights', 'Travel insurance', 'Club hire', 'Meals not stated'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival', description: 'Transfer from Faro, check in and loosen up on the practice ground.' },
      { label: 'Days 2–4', title: 'Round a day', description: 'Morning tee times, afternoons at the beach, spa or the 19th hole.' },
      { label: 'Day 5', title: 'Departure', description: 'Late breakfast and transfer back to Faro.' },
    ],
    hotelName: null, boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 12,
    slug: 'belek-golf-week',
    title: 'Belek All-Inclusive Golf Week',
    tagline: 'Turkey’s golf riviera — championship courses and a five-star all-inclusive base.',
    destinationSlug: 'turkey', destinationName: 'Turkey', region: 'Europe',
    brand: 'golf', category: 'Family', nights: 6, days: 7,
    priceFrom: 6900, currency: 'AED',
    heroImage: img('photo-1764562155715-40df5778946e'),
    gallery: [img('photo-1764562155715-40df5778946e', 1200)],
    overview: [
      'Belek stacks more championship golf into one strip of Mediterranean coast than almost anywhere on earth — and wraps it in genuinely excellent all-inclusive resorts. Four rounds, unlimited food and drink, and a flight time under four hours from the Gulf.',
    ],
    highlights: [
      'Four rounds across Belek’s championship courses',
      '5★ all-inclusive resort — meals and drinks covered',
      'Perfect for mixed groups: pools, spa and beach for non-golfers',
      'Short flight from the UAE — no jet lag golf',
    ],
    includes: [
      '6 nights ultra all-inclusive in a 5★ golf resort',
      '4 rounds of golf with transfers to the courses',
      'Return airport transfers',
      'Group tee times arranged together',
    ],
    excludes: ['International flights', 'Travel insurance', 'Buggies and club hire'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival in Belek', description: 'Transfer from Antalya, resort check-in, welcome dinner.' },
      { label: 'Days 2–6', title: 'Golf and resort life', description: 'Four rounds spread across five days — the rest is pools, spa, beach and the buffet of your dreams.' },
      { label: 'Day 7', title: 'Departure', description: 'Transfer back to Antalya airport.' },
    ],
    hotelName: null, boardBasis: 'Ultra All Inclusive',
    featured: true, status: 'published',
  },
  {
    id: 13,
    slug: 'mauritius-golf-and-beach',
    title: 'Mauritius Golf & Beach',
    tagline: 'Ocean-view fairways and lagoon afternoons — golf where the Indian Ocean shows off.',
    destinationSlug: 'mauritius', destinationName: 'Mauritius', region: 'Indian Ocean',
    brand: 'golf', category: 'Honeymoon', nights: 6, days: 7,
    priceFrom: 11200, currency: 'AED',
    heroImage: img('photo-1513415277900-a62401e19be4'),
    gallery: [img('photo-1513415277900-a62401e19be4', 1200)],
    overview: [
      'Few places blend a serious golf trip with a proper beach holiday like Mauritius. Stay at a beachfront resort with its own championship course, play three included rounds between mountain and sea, and hand the non-golfers a lagoon they’ll never want to leave.',
    ],
    highlights: [
      'Three rounds on a resort championship course',
      'Beachfront 5★ resort on a swimmable lagoon',
      'Half-board dining with ocean-view restaurants',
      'Ideal golf-plus-honeymoon or family combination',
    ],
    includes: [
      '6 nights half board in a 5★ beach resort',
      '3 rounds of golf with shared buggy',
      'Return airport transfers',
      'Green-fee discounts on additional rounds',
    ],
    excludes: ['International flights', 'Travel insurance', 'Lunches and premium drinks'],
    itinerary: [
      { label: 'Day 1', title: 'Arrival', description: 'Private transfer across the island, sunset check-in on the lagoon.' },
      { label: 'Days 2–6', title: 'Golf and lagoon days', description: 'Three morning rounds woven between beach days, catamaran trips and spa time.' },
      { label: 'Day 7', title: 'Departure', description: 'Last swim, transfer to the airport.' },
    ],
    hotelName: null, boardBasis: 'Half Board',
    featured: true, status: 'published',
  },

  /* ───────────────────────────── Cruises ───────────────────────────── */
  {
    id: 14,
    slug: 'arabian-gulf-cruise',
    title: 'Arabian Gulf Cruise from Dubai',
    tagline: 'Skylines, souks and a desert island — a long weekend at sea, no flight required.',
    destinationSlug: 'arabian-gulf', destinationName: 'Arabian Gulf', region: 'Cruise Seas',
    brand: 'cruises', category: 'Cruises', nights: 3, days: 4,
    priceFrom: 2400, currency: 'AED',
    heroImage: img('photo-1722502831583-b4e93ecc6027'),
    gallery: [img('photo-1722502831583-b4e93ecc6027', 1200)],
    overview: [
      'Board in Dubai after breakfast, unpack once and wake up somewhere new every morning. Gulf sailings are the easiest cruise there is for UAE residents: modern mega-ships, family entertainment all day, and ports from Doha to a private desert island.',
    ],
    highlights: [
      'Sails from Dubai — drive to the terminal, no flights',
      'Full-board dining and headline entertainment included',
      'Ports vary by season: Abu Dhabi, Doha, Bahrain, private island',
      'Great value family cabins and kids’ clubs',
    ],
    includes: [
      '3 nights full board in your chosen cabin grade',
      'All main-restaurant dining and entertainment',
      'Port charges and taxes',
      'PCT cruise check-in assistance in Dubai',
    ],
    excludes: ['Drinks packages and speciality dining', 'Shore excursions', 'Gratuities', 'Travel insurance'],
    itinerary: [
      { label: 'Day 1', title: 'Embark in Dubai', description: 'Board from mid-day, explore the ship, sail-away past the Dubai skyline at dusk.' },
      { label: 'Days 2–3', title: 'Ports of the Gulf', description: 'A new port each morning — city tour, beach day or stay aboard and own the pool deck.' },
      { label: 'Day 4', title: 'Return to Dubai', description: 'Breakfast on board, disembark and home by lunch.' },
    ],
    hotelName: null, boardBasis: 'Full Board at sea',
    featured: true, status: 'published',
  },
  {
    id: 15,
    slug: 'mediterranean-highlights-cruise',
    title: 'Mediterranean Highlights Fly-Cruise',
    tagline: 'Rome, the Riviera and Barcelona in one week — with your hotel sailing alongside you.',
    destinationSlug: 'mediterranean', destinationName: 'Mediterranean', region: 'Cruise Seas',
    brand: 'cruises', category: 'Cruises', nights: 7, days: 8,
    priceFrom: 7800, currency: 'AED',
    heroImage: img('photo-1655042490932-bd2cc9ea6f9b'),
    gallery: [img('photo-1655042490932-bd2cc9ea6f9b', 1200), img('photo-1613395877344-13d4a8e0d49e', 1200)],
    overview: [
      'The classic western Mediterranean loop: seven nights linking Italy, France and Spain with sea days built in to actually relax. We bundle the flights from the UAE, pre-cruise hotel night and transfers so the whole journey is one seamless booking.',
    ],
    highlights: [
      'Seven nights visiting Italy, France and Spain',
      'Flights from the UAE and transfers bundled in',
      'Pre-cruise hotel night included',
      'Balcony cabins at remarkably sharp rates',
    ],
    includes: [
      '7 nights full board on a premium ship',
      'Return flights from Dubai and all transfers',
      '1 pre-cruise hotel night',
      'Port charges and taxes',
    ],
    excludes: ['Drinks packages', 'Shore excursions', 'Gratuities', 'Travel insurance'],
    itinerary: [
      { label: 'Day 1', title: 'Fly to Rome', description: 'Overnight in the Eternal City — first pasta of the week.' },
      { label: 'Days 2–7', title: 'The western Med', description: 'Ports typically include Naples, Florence/Pisa, the French Riviera and Palma before Barcelona.' },
      { label: 'Day 8', title: 'Barcelona → home', description: 'Disembark, city time if your flight allows, fly back to the UAE.' },
    ],
    hotelName: null, boardBasis: 'Full Board at sea',
    featured: true, status: 'published',
  },
  {
    id: 16,
    slug: 'norwegian-fjords-cruise',
    title: 'Norwegian Fjords Cruise',
    tagline: 'Waterfalls off the balcony and midnight light — nature’s greatest cruise corridor.',
    destinationSlug: 'northern-europe', destinationName: 'Northern Europe', region: 'Cruise Seas',
    brand: 'cruises', category: 'Cruises', nights: 7, days: 8,
    priceFrom: 9400, currency: 'AED',
    heroImage: img('photo-1518124880777-cf8c82231ffb'),
    gallery: [img('photo-1518124880777-cf8c82231ffb', 1200)],
    overview: [
      'There is no better way to see the fjords than from the water — glass-calm channels, thousand-metre cliffs and villages you can only reach by sea. Summer sailings bring near-endless daylight; pack a jumper and let the scenery do the work.',
    ],
    highlights: [
      'Sail deep into Geiranger and Sogne-region fjords',
      'Long summer daylight — scenery until midnight',
      'Flights from the UAE and transfers arranged',
      'Balcony cabins strongly recommended (and priced well)',
    ],
    includes: [
      '7 nights full board',
      'Return flights from Dubai and transfers',
      'Port charges and taxes',
      'PCT pre-departure guide to every port',
    ],
    excludes: ['Drinks packages', 'Shore excursions', 'Gratuities', 'Travel insurance'],
    itinerary: [
      { label: 'Day 1', title: 'Fly to Southampton or Bergen', description: 'Join your ship and settle in.' },
      { label: 'Days 2–7', title: 'Into the fjords', description: 'Waterfall-lined channels, mountain railways, kayaking and villages like Flåm and Olden.' },
      { label: 'Day 8', title: 'Home', description: 'Disembark and fly back to the UAE.' },
    ],
    hotelName: null, boardBasis: 'Full Board at sea',
    featured: true, status: 'published',
  },
  {
    id: 17,
    slug: 'greek-islands-cruise',
    title: 'Greek Islands Cruise',
    tagline: 'Santorini at sunset, Mykonos by night — the Aegean, island by island.',
    destinationSlug: 'mediterranean', destinationName: 'Mediterranean', region: 'Cruise Seas',
    brand: 'cruises', category: 'Cruises', nights: 7, days: 8,
    priceFrom: 8200, currency: 'AED',
    heroImage: img('photo-1613395877344-13d4a8e0d49e'),
    gallery: [img('photo-1613395877344-13d4a8e0d49e', 1200), img('photo-1655042490932-bd2cc9ea6f9b', 1200)],
    overview: [
      'Island-hopping the Aegean by ferry is a logistics project; by cruise ship it’s a holiday. Wake up under Santorini’s caldera, spend evenings in Mykonos town, and slot in ancient Ephesus or Rhodes — all from one very comfortable floating base.',
    ],
    highlights: [
      'Santorini, Mykonos and Crete on one sailing',
      'Evening departures — real time ashore',
      'Flights from the UAE bundled in',
      'Adults-only and family ship options',
    ],
    includes: [
      '7 nights full board',
      'Return flights from Dubai and transfers',
      'Port charges and taxes',
    ],
    excludes: ['Drinks packages', 'Shore excursions', 'Gratuities', 'Travel insurance'],
    itinerary: [
      { label: 'Day 1', title: 'Fly to Athens', description: 'Embark in Piraeus with the Acropolis on the skyline.' },
      { label: 'Days 2–7', title: 'The Aegean', description: 'Santorini, Mykonos, Crete and a Turkish coast call — beach mornings, taverna evenings.' },
      { label: 'Day 8', title: 'Athens → home', description: 'Disembark and fly back to the UAE.' },
    ],
    hotelName: null, boardBasis: 'Full Board at sea',
    featured: true, status: 'published',
  },

  /* ───────────────────────────── Staycations ───────────────────────────── */
  {
    id: 18,
    slug: 'ras-al-khaimah-beach-escape',
    title: 'Ras Al Khaimah Beach Escape',
    tagline: 'An hour up the coast, a world quieter — beach mornings under the Hajar mountains.',
    destinationSlug: 'united-arab-emirates', destinationName: 'United Arab Emirates', region: 'Middle East',
    brand: 'staycations', category: 'Staycations', nights: 2, days: 3,
    priceFrom: 1200, currency: 'AED',
    heroImage: img('photo-1690467699639-3a3c80033e81'),
    gallery: [img('photo-1690467699639-3a3c80033e81', 1200)],
    overview: [
      'RAK has quietly become the UAE’s best-value beach weekend: long white-sand resorts, mountain backdrops and rates Dubai hasn’t seen in years. We hold preferred rates with breakfast and late checkout at the emirate’s standout properties.',
    ],
    highlights: [
      'White-sand beach resorts at genuinely sharp rates',
      'Jebel Jais nearby — via ferrata and the world’s longest zipline',
      'Breakfast and late checkout through PCT rates',
      'Under an hour from Dubai',
    ],
    includes: ['2 nights at a 5★ beach resort', 'Daily breakfast for two', 'Late checkout where available'],
    excludes: ['Transport', 'Tourism fee (paid at checkout)', 'Lunches and dinners'],
    itinerary: [
      { label: 'Day 1', title: 'Arrive & unwind', description: 'Check in, beach afternoon, shisha sunset.' },
      { label: 'Day 2', title: 'Mountains or beach', description: 'Jebel Jais adventure morning or full resort mode — your call.' },
      { label: 'Day 3', title: 'Slow departure', description: 'Late checkout, brunch, easy drive home.' },
    ],
    hotelName: 'Your choice of partner resorts', boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 19,
    slug: 'saadiyat-island-retreat',
    title: 'Saadiyat Island Retreat',
    tagline: 'Abu Dhabi’s most beautiful beach, the Louvre next door — culture and calm in one weekend.',
    destinationSlug: 'united-arab-emirates', destinationName: 'United Arab Emirates', region: 'Middle East',
    brand: 'staycations', category: 'Staycations', nights: 2, days: 3,
    priceFrom: 1900, currency: 'AED',
    heroImage: img('photo-1613835579153-9bfe32e50da6'),
    gallery: [img('photo-1613835579153-9bfe32e50da6', 1200)],
    overview: [
      'Saadiyat is the staycation that doesn’t feel like one: a protected white-sand beach where turtles nest, dune boardwalks, and the Louvre Abu Dhabi ten minutes away. Pair a beachfront resort with a cultural morning and you’ve had two holidays in one weekend.',
    ],
    highlights: [
      'Protected white-sand beach — the UAE’s finest',
      'Louvre Abu Dhabi and Saadiyat Cultural District nearby',
      'Turtle-nesting beach walks in season',
      'PCT perks: breakfast, resort credit where available',
    ],
    includes: ['2 nights at a 5★ Saadiyat resort', 'Daily breakfast for two', 'Resort credit where available'],
    excludes: ['Transport', 'Museum tickets', 'Lunches and dinners'],
    itinerary: [
      { label: 'Day 1', title: 'Beach day', description: 'Check in and straight to that beach — dinner on the sand.' },
      { label: 'Day 2', title: 'Louvre morning', description: 'Culture before noon, pool after, spa before dinner.' },
      { label: 'Day 3', title: 'Departure', description: 'Sunrise beach walk, breakfast, home by afternoon.' },
    ],
    hotelName: 'Your choice of partner resorts', boardBasis: 'Bed & Breakfast',
    featured: true, status: 'published',
  },
  {
    id: 20,
    slug: 'desert-oasis-staycation',
    title: 'Desert Oasis Staycation',
    tagline: 'One night among the dunes — falconry at dawn, fire-lit dinners under the stars.',
    destinationSlug: 'united-arab-emirates', destinationName: 'United Arab Emirates', region: 'Middle East',
    brand: 'staycations', category: 'Staycations', nights: 1, days: 2,
    priceFrom: 950, currency: 'AED',
    heroImage: img('photo-1518684079-3c830dcef090'),
    gallery: [img('photo-1518684079-3c830dcef090', 1200)],
    overview: [
      'The reset button: a desert resort under an hour from the city where the itinerary is sunrise, sand and silence. Most stays include dune activities and a dinner that tastes better for being eaten by firelight.',
    ],
    highlights: [
      'Desert resorts and luxury camps across the emirates',
      'Dune drives, camel treks and falconry on site',
      'Star-lit dinners included at most properties',
      'The best one-night reset in the UAE',
    ],
    includes: ['1 night in a desert resort or luxury camp', 'Breakfast and select dinner experiences', 'Selected on-site activities'],
    excludes: ['Transport', 'Premium experiences', 'Tourism fee'],
    itinerary: [
      { label: 'Day 1', title: 'Into the dunes', description: 'Afternoon arrival, sunset dune drive, dinner by the fire.' },
      { label: 'Day 2', title: 'Dawn and home', description: 'Sunrise camel trek or falconry, big breakfast, back to the city.' },
    ],
    hotelName: 'Your choice of partner resorts', boardBasis: 'Half Board',
    featured: true, status: 'published',
  },
];

export const sampleTestimonials = [
  {
    quote: 'Every detail was handled — transfers, dinners, even a birthday cake in the villa. The best travel company we have used in the UAE.',
    name: 'Sarah & James M.', trip: 'Varu by Atmosphere, Maldives',
  },
  {
    quote: 'Our Georgia tour felt private and personal. The guide became a friend and the itinerary was paced perfectly.',
    name: 'The Al Rashid family', trip: 'Grand Georgia Discovery',
  },
  {
    quote: 'From first enquiry to the quote PDF to the trip itself — professional at every step. Japan was flawless.',
    name: 'Daniel K.', trip: 'Japan Golden Route',
  },
];

export const SERVICES = [
  { title: 'Tailor-made packages', text: 'Flights, hotels and experiences shaped around you — not off a shelf.' },
  { title: 'Cruises', text: 'Local Arabian Gulf sailings and international itineraries with the major lines.' },
  { title: 'Staycations', text: 'Preferred rates at the UAE’s finest resorts, often with extras included.' },
  { title: 'Travel insurance', text: 'Comprehensive cover arranged in minutes alongside your booking.' },
  { title: 'Car hire', text: 'Self-drive and chauffeur options at your destination, ready on arrival.' },
  { title: 'Airport lounges', text: 'Lounge access worldwide to start the holiday before boarding.' },
];
