'use server';

import { revalidatePath } from 'next/cache';
import { requireAdmin } from '@/lib/admin/guard';
import { pcstClient, isPcstConfigured } from '@/lib/pcst';
import { revalidatePcst } from '@/lib/pcst-revalidate';
import { extractDay, extractTripHighlights, EXTRACT_MODEL } from '@/lib/itinerary/extract';
import type { StructuredDay } from '@/lib/itinerary/schema';

/**
 * Builds the scannable day-by-day layer on School Trips itineraries.
 *
 * These write to the School Trips database, so `revalidatePath` here would do
 * nothing for the public site — that site is statically generated by a
 * different deployment. Every write therefore pings its revalidate endpoint.
 */

export type ItineraryResult = { ok: true; days?: number; failed?: number } | { ok: false; error: string };

const toRow = (s: StructuredDay) => ({
  display_title: s.displayTitle,
  summary: s.summary,
  primary_location: s.primaryLocation,
  highlights: s.highlights.map((h) => ({
    name: h.name, summary: h.summary, type: h.type, location: h.location,
    conditional: h.conditional, conditional_text: h.conditionalText,
  })),
  learning_focus: s.learningFocus,
  experience_types: s.experienceTypes,
  locations: s.locations,
  meals: s.meals,
  transport: s.transport,
  notices: s.notices,
  review_flags: s.reviewFlags,
  structured_at: new Date().toISOString(),
  structured_model: EXTRACT_MODEL,
});

/** Rebuild the journey rail and trip highlights from the structured days. */
async function rollUpTrip(tripId: number) {
  const db = pcstClient();
  const { data: trip } = await db
    .from('trips')
    .select('id, slug, title, itinerary_days(sort_order, display_title, summary, primary_location, highlights, structured_at)')
    .eq('id', tripId)
    .maybeSingle();
  if (!trip) return;

  const days = ((trip.itinerary_days as any[]) ?? [])
    .filter((d) => d.structured_at)
    .sort((a, b) => a.sort_order - b.sort_order);
  if (!days.length) return;

  const journey: { location: string; from_day: number; to_day: number }[] = [];
  days.forEach((d, i) => {
    const place = (d.primary_location ?? '').trim();
    if (!place) return;
    const dayNumber = i + 1;
    const last = journey[journey.length - 1];
    if (last && last.location.toLowerCase() === place.toLowerCase()) last.to_day = dayNumber;
    else journey.push({ location: place, from_day: dayNumber, to_day: dayNumber });
  });

  let highlights: string[] = [];
  try {
    highlights = await extractTripHighlights(
      trip.title,
      days.map((d, i) => ({
        dayNumber: i + 1,
        title: d.display_title ?? '',
        summary: d.summary ?? '',
        highlights: ((d.highlights as any[]) ?? []).map((h) => h.name),
      }))
    );
  } catch {
    // A failed rollup must not undo the per-day work.
  }

  await db
    .from('trips')
    .update({ journey, trip_highlights: highlights, structured_at: new Date().toISOString() })
    .eq('id', tripId);

  await revalidatePcst(trip.slug);
}

/** Analyse every day of a School Trips itinerary. */
export async function structureStTrip(
  tripId: number,
  { force = true }: { force?: boolean } = {}
): Promise<ItineraryResult> {
  await requireAdmin();
  if (!isPcstConfigured()) return { ok: false, error: 'School Trips database is not configured.' };
  if (!process.env.ANTHROPIC_API_KEY) return { ok: false, error: 'ANTHROPIC_API_KEY is not configured.' };

  const db = pcstClient();
  const { data: trip } = await db
    .from('trips')
    .select('id, slug, title, subjects(name), countries(name), itinerary_days(id, sort_order, label, title, description, structured_at)')
    .eq('id', tripId)
    .maybeSingle();
  if (!trip) return { ok: false, error: 'Trip not found.' };

  const days = ((trip.itinerary_days as any[]) ?? []).sort((a, b) => a.sort_order - b.sort_order);
  if (!days.length) return { ok: false, error: 'This trip has no itinerary days yet.' };

  // The days are independent, so analyse them concurrently — sequentially this
  // pass takes over a minute and outlives the function timeout.
  const results = await Promise.all(
    days.map(async (day, i) => {
      if (!force && day.structured_at) return 'skipped';
      if (!day.description?.trim()) return 'skipped';
      try {
        const structured = await extractDay({
          dayNumber: i + 1,
          totalDays: days.length,
          label: day.label,
          title: day.title,
          description: day.description,
          tripTitle: trip.title,
          subject: (trip.subjects as any)?.name ?? null,
          country: (trip.countries as any)?.name ?? null,
        });
        const { error } = await db.from('itinerary_days').update(toRow(structured)).eq('id', day.id);
        if (error) throw new Error(error.message);
        return 'done';
      } catch {
        return 'failed';
      }
    })
  );
  const done = results.filter((r) => r === 'done').length;
  const failed = results.filter((r) => r === 'failed').length;

  await rollUpTrip(tripId);
  revalidatePath(`/admin/school-trips/trips/${tripId}`);
  return { ok: true, days: done, failed };
}

/** Regenerate one day. Never touches the original description. */
export async function regenerateStDay(dayId: number): Promise<ItineraryResult> {
  await requireAdmin();
  if (!isPcstConfigured()) return { ok: false, error: 'School Trips database is not configured.' };

  const db = pcstClient();
  const { data: day } = await db
    .from('itinerary_days')
    .select('id, trip_id, sort_order, label, title, description')
    .eq('id', dayId)
    .maybeSingle();
  if (!day) return { ok: false, error: 'Day not found.' };
  if (!day.description?.trim()) return { ok: false, error: 'This day has no description to work from.' };

  const { data: trip } = await db
    .from('trips')
    .select('id, title, subjects(name), countries(name), itinerary_days(id, sort_order)')
    .eq('id', day.trip_id)
    .maybeSingle();
  if (!trip) return { ok: false, error: 'Trip not found.' };

  const ordered = ((trip.itinerary_days as any[]) ?? []).sort((a, b) => a.sort_order - b.sort_order);
  const position = ordered.findIndex((d) => d.id === dayId) + 1;

  try {
    const structured = await extractDay({
      dayNumber: position || day.sort_order,
      totalDays: ordered.length,
      label: day.label,
      title: day.title,
      description: day.description,
      tripTitle: trip.title,
      subject: (trip.subjects as any)?.name ?? null,
      country: (trip.countries as any)?.name ?? null,
    });
    const { error } = await db.from('itinerary_days').update(toRow(structured)).eq('id', dayId);
    if (error) return { ok: false, error: error.message };
  } catch (e: any) {
    return { ok: false, error: `Could not analyse this day: ${e.message}` };
  }

  await rollUpTrip(day.trip_id);
  revalidatePath(`/admin/school-trips/trips/${day.trip_id}`);
  return { ok: true, days: 1, failed: 0 };
}
