import type { CatalogueEntry } from './types';

/** Wave 3 — ranks 41–60. Portfolio breadth: launch content, grown over time. */
export const WAVE3: CatalogueEntry[] = [
  {
    slug: 'saudi-arabia', name: 'Saudi Arabia', region: 'Middle East', priorityRank: 41,
    strapline: 'The region’s great opening.',
    blurb: 'AlUla’s carved tombs, Red Sea reefs and a cultural scene moving at speed.',
    tags: ['Culture', 'Desert', 'History', 'Short Break', 'Adventure'],
    seasonality: { best: [11, 12, 1, 2], good: [3, 10], possible: [4, 5, 6, 7, 8, 9] },
    subDestinations: [
      { heading: 'AlUla', body: 'Hegra’s Nabataean tombs — Petra’s sister, without the crowds.' },
      { heading: 'Jeddah', body: 'Al Balad’s coral-stone old town and the Red Sea corniche.' },
      { heading: 'Riyadh', body: 'Diriyah’s restored birthplace of the kingdom and a booming arts district.' },
    ],
    experiences: [
      { heading: 'Hegra by vintage Land Rover', body: 'Carved tombs at golden hour.' },
      { heading: 'Elephant Rock sunsets', body: 'AlUla’s sandstone icon with coffee in the dunes.' },
      { heading: 'Old Jeddah walk', body: 'Coral houses and latticed balconies in Al Balad.' },
    ],
    stay: [
      { heading: 'AlUla desert resorts', body: 'Canyon hideaways among the rocks.' },
      { heading: 'Red Sea beach hotels', body: 'New-generation resorts on untouched reefs.' },
    ],
    journeyIdeas: ['AlUla Long Weekend', 'Jeddah & the Red Sea', 'Riyadh Culture & Design', 'Saudi Heritage & Desert Journey'],
  },
  {
    slug: 'jordan', name: 'Jordan', region: 'Middle East', priorityRank: 42,
    strapline: 'Ancient wonders, modern discoveries.',
    blurb: 'Petra at dawn, Wadi Rum by starlight, the Dead Sea in between.',
    tags: ['History', 'Desert', 'Family', 'Adventure', 'Culture', 'Short Break'],
    seasonality: { best: [3, 4, 5, 9, 10, 11], good: [2, 12], possible: [1, 6, 7, 8] },
    subDestinations: [
      { heading: 'Petra', body: 'The Siq, the Treasury and the Monastery climb.' },
      { heading: 'Wadi Rum', body: 'Lawrence’s desert — 4x4 dunes and Bedouin camps.' },
      { heading: 'The Dead Sea', body: 'The lowest point on Earth, floating included.' },
    ],
    experiences: [
      { heading: 'Petra at opening', body: 'The Treasury in first light, before the crowds.' },
      { heading: 'Wadi Rum stargazing', body: 'Zero light pollution, infinite sky.' },
      { heading: 'Dead Sea float & mud', body: 'The world’s strangest swim.' },
    ],
    stay: [
      { heading: 'Bedouin bubble camps', body: 'Dome tents with desert panoramas.' },
      { heading: 'Dead Sea spa resorts', body: 'Infinity pools above the salt.' },
    ],
    journeyIdeas: ['Petra, Wadi Rum & Dead Sea', 'Jordan Family Adventure', 'Jordan Luxury Long Weekend', 'Amman to Aqaba Road Trip'],
  },
  {
    slug: 'cyprus', name: 'Cyprus', region: 'Europe', priorityRank: 43,
    strapline: 'The Mediterranean’s long summer.',
    blurb: 'Family beaches, mountain villages and warm seas from April to November.',
    tags: ['Beach', 'Family', 'Villas', 'Couples', 'History'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8, 11], possible: [12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Paphos', body: 'Harbour castle, mosaics and family resort country.' },
      { heading: 'The Troodos', body: 'Painted churches and cool mountain villages.' },
      { heading: 'Ayia Napa & Protaras', body: 'The island’s clearest swimming water.' },
    ],
    experiences: [
      { heading: 'Blue Lagoon boat days', body: 'Akamas swimming stops in gin-clear water.' },
      { heading: 'Meze marathons', body: 'Twenty small plates, one long taverna afternoon.' },
      { heading: 'Troodos village drives', body: 'Halloumi makers and mountain monasteries.' },
    ],
    stay: [
      { heading: 'Family beach resorts', body: 'Waterparks and kids’ clubs on sandy bays.' },
      { heading: 'Private villas', body: 'Pools and barbecues for multi-generation stays.' },
    ],
    journeyIdeas: ['Cyprus Family Beach Holiday', 'Paphos & Troodos Mountains', 'Cyprus Villa Escape', 'Food, Villages & Coast'],
  },
  {
    slug: 'malta', name: 'Malta', region: 'Europe', priorityRank: 44,
    strapline: 'Seven thousand years in a harbour.',
    blurb: 'Honey-stone Valletta, blue grottos and English-speaking ease in the middle of the Med.',
    tags: ['Culture', 'History', 'Diving', 'Family', 'Short Break'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8, 11], possible: [12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Valletta', body: 'The knights’ golden capital — Europe’s smallest, sunniest.' },
      { heading: 'Gozo', body: 'Slower, greener sister island of salt pans and citadels.' },
      { heading: 'Mdina', body: 'The silent city’s lamplit lanes.' },
    ],
    experiences: [
      { heading: 'Grand Harbour cruise', body: 'Fortresses from the waterline.' },
      { heading: 'Blue Grotto & Comino', body: 'The famous lagoon before the party boats.' },
      { heading: 'Megalithic temples', body: 'Structures older than the pyramids.' },
    ],
    stay: [
      { heading: 'Valletta palazzo boutiques', body: 'Sixteenth-century stone, rooftop plunge pools.' },
      { heading: 'Seafront family resorts', body: 'St Julian’s and Mellieha bases.' },
    ],
    journeyIdeas: ['Malta & Gozo', 'Malta Family Summer', 'Valletta Culture Weekend', 'Malta Diving & Coast'],
  },
  {
    slug: 'albania', name: 'Albania', region: 'Europe', priorityRank: 45,
    strapline: 'The Mediterranean’s last surprise.',
    blurb: 'Riviera coves, UNESCO towns and alpine passes at prices from another decade.',
    tags: ['Beach', 'Value', 'Road Trip', 'Adventure', 'Culture'],
    seasonality: { best: [5, 6, 9], good: [4, 7, 8, 10], possible: [11, 12, 1, 2, 3] },
    subDestinations: [
      { heading: 'The Riviera', body: 'Ksamil and Dhermi — Ionian water, Greek-island blue.' },
      { heading: 'Gjirokastër & Berat', body: 'UNESCO stone towns stacked up hillsides.' },
      { heading: 'The Accursed Mountains', body: 'The Balkans’ wildest hiking.' },
    ],
    experiences: [
      { heading: 'Blue Eye spring', body: 'A fifty-metre-deep natural pool of impossible colour.' },
      { heading: 'Butrint ruins', body: 'Greek, Roman and Venetian layers in a lagoon national park.' },
      { heading: 'Riviera road trip', body: 'The Llogara Pass down to empty beaches.' },
    ],
    stay: [
      { heading: 'Boutique beach hotels', body: 'Small, family-run and right on the water.' },
      { heading: 'Ottoman guesthouses', body: 'Stone mansions in Berat and Gjirokastër.' },
    ],
    journeyIdeas: ['Albanian Riviera Road Trip', 'Tirana & the Coast', 'Albania Family Adventure', 'Mountains, Villages & Adriatic'],
  },
  {
    slug: 'serbia', name: 'Serbia', region: 'Europe', priorityRank: 46,
    strapline: 'The Balkans’ beating heart.',
    blurb: 'Belgrade’s riverside energy, monastery valleys and mountain spa towns.',
    tags: ['City Break', 'Value', 'Food', 'Nightlife', 'Culture'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8, 12], possible: [1, 2, 3, 11] },
    subDestinations: [
      { heading: 'Belgrade', body: 'Fortress sunsets where the Sava meets the Danube.' },
      { heading: 'Novi Sad', body: 'Habsburg charm and the Petrovaradin fortress.' },
    ],
    experiences: [
      { heading: 'Kafana nights', body: 'Traditional taverns with live tamburica bands.' },
      { heading: 'Splavovi river clubs', body: 'Belgrade’s floating nightlife.' },
      { heading: 'Fruska Gora monasteries', body: 'Wine and frescoes in the holy hills.' },
    ],
    stay: [
      { heading: 'Design hotels in Dorćol', body: 'Belgrade’s coolest quarter.' },
    ],
    journeyIdeas: ['Belgrade City Break', 'Serbia Food & Wine Escape', 'Belgrade & Novi Sad', 'Serbia Winter Weekend'],
  },
  {
    slug: 'hungary', name: 'Hungary', region: 'Europe', priorityRank: 47,
    strapline: 'Grandeur on the Danube.',
    blurb: 'Budapest’s thermal baths, ruin bars and parliament views — a city built for long weekends.',
    tags: ['City Break', 'Spa', 'Festive', 'Couples', 'Value'],
    seasonality: { best: [5, 6, 9, 12], good: [4, 7, 8, 10], possible: [1, 2, 3, 11] },
    subDestinations: [
      { heading: 'Buda', body: 'Castle hill, Fisherman’s Bastion and thermal baths.' },
      { heading: 'Pest', body: 'Parliament, ruin bars and café grandeur.' },
    ],
    experiences: [
      { heading: 'Széchenyi baths morning', body: 'Steam rising off outdoor pools, chess in the water.' },
      { heading: 'Danube dinner cruise', body: 'Parliament lit gold from the river.' },
      { heading: 'Ruin-bar crawl', body: 'Szimpla Kert and the district that invented the genre.' },
    ],
    stay: [
      { heading: 'Danube-view grand hotels', body: 'Chain Bridge panoramas.' },
      { heading: 'Jewish-quarter boutiques', body: 'Design stays near the ruin bars.' },
    ],
    journeyIdeas: ['Budapest Long Weekend', 'Budapest Spa & Food Escape', 'Budapest Christmas Markets', 'Vienna, Budapest & Prague'],
  },
  {
    slug: 'slovenia', name: 'Slovenia', region: 'Europe', priorityRank: 48,
    strapline: 'Europe in miniature, emerald edition.',
    blurb: 'Lake Bled’s island church, Julian Alps adventures and a capital of riverside cafés.',
    tags: ['Nature', 'Lakes', 'Family', 'Adventure', 'Road Trip'],
    seasonality: { best: [5, 6, 7, 8, 9], good: [4, 10, 12], possible: [1, 2, 3, 11] },
    subDestinations: [
      { heading: 'Lake Bled & Bohinj', body: 'The island church and its wilder, quieter neighbour.' },
      { heading: 'Ljubljana', body: 'Dragon bridges and café-lined embankments.' },
      { heading: 'The Soča Valley', body: 'Turquoise rapids and Julian Alps trails.' },
    ],
    experiences: [
      { heading: 'Pletna boat to Bled Island', body: 'Ring the wishing bell, eat the cream cake.' },
      { heading: 'Soča rafting', body: 'The most beautiful whitewater in Europe.' },
      { heading: 'Postojna & Predjama', body: 'Cave trains and a castle in a cliff.' },
    ],
    stay: [
      { heading: 'Lakefront classics at Bled', body: 'Belle-époque balconies over the water.' },
      { heading: 'Alpine eco-lodges', body: 'Glamping among the peaks.' },
    ],
    journeyIdeas: ['Ljubljana & Lake Bled', 'Slovenia Family Adventure', 'Alps to Adriatic Road Trip', 'Slovenia Food & Wellness'],
  },
  {
    slug: 'norway', name: 'Norway', region: 'Europe', priorityRank: 49,
    strapline: 'Nature at full volume.',
    blurb: 'Mile-deep fjords, midnight sun and northern lights — the great summer cool-down.',
    tags: ['Nature', 'Fjords', 'Northern Lights', 'Family', 'Cruise'],
    seasonality: { best: [6, 7, 8], good: [5, 9, 12, 1, 2, 3], possible: [4, 10, 11] },
    subDestinations: [
      { heading: 'The fjords', body: 'Geiranger and Nærøyfjord — UNESCO water canyons.' },
      { heading: 'Bergen', body: 'Wooden wharves and seven mountains.' },
      { heading: 'Tromsø & the north', body: 'Aurora capital above the Arctic Circle.' },
    ],
    experiences: [
      { heading: 'Flåm railway & fjord cruise', body: 'The classic Norway in a Nutshell loop.' },
      { heading: 'Midnight-sun hikes', body: 'Pulpit Rock with the sun refusing to set.' },
      { heading: 'Aurora safaris', body: 'Tromsø’s dancing skies, September to March.' },
    ],
    stay: [
      { heading: 'Fjord-edge hotels', body: 'Balconies over mirror water.' },
      { heading: 'Arctic glass cabins', body: 'Northern lights from the pillow.' },
    ],
    journeyIdeas: ['Norwegian Fjords Journey', 'Norway Family Summer', 'Northern Lights Escape', 'Oslo, Bergen & Scenic Rail'],
  },
  {
    slug: 'sweden', name: 'Sweden', region: 'Europe', priorityRank: 50,
    strapline: 'Design, forests and fika.',
    blurb: 'Stockholm’s island city, archipelago summers and Lapland’s ice hotels.',
    tags: ['City Break', 'Design', 'Family', 'Winter', 'Nature'],
    seasonality: { best: [6, 7, 8], good: [5, 9, 12, 1, 2], possible: [3, 4, 10, 11] },
    subDestinations: [
      { heading: 'Stockholm', body: 'Gamla Stan lanes and thirty thousand archipelago islands.' },
      { heading: 'Swedish Lapland', body: 'Ice hotels, dog sleds and aurora skies.' },
      { heading: 'Gothenburg & the west', body: 'Seafood safaris and car-free island chains.' },
    ],
    experiences: [
      { heading: 'Archipelago boat days', body: 'Island-hop to swimming rocks and summer cafés.' },
      { heading: 'Fika, properly', body: 'Cinnamon buns as a daily ritual.' },
      { heading: 'Icehotel night', body: 'Sleep on reindeer skins at minus five, beautifully.' },
    ],
    stay: [
      { heading: 'Gamla Stan boutiques', body: 'Seventeenth-century beams, Nordic design.' },
      { heading: 'Archipelago inns', body: 'Jetty mornings, sauna evenings.' },
    ],
    journeyIdeas: ['Stockholm & Archipelago', 'Swedish Lapland Winter', 'Sweden Family Summer', 'Design, Food & Nature'],
  },
  {
    slug: 'denmark', name: 'Denmark', region: 'Europe', priorityRank: 51,
    strapline: 'The happiest city break in Europe.',
    blurb: 'Copenhagen’s harbour baths, Tivoli evenings and the restaurant scene that changed food.',
    tags: ['City Break', 'Family', 'Food', 'Design', 'Cycling'],
    seasonality: { best: [5, 6, 7, 8], good: [4, 9, 12], possible: [1, 2, 3, 10, 11] },
    subDestinations: [
      { heading: 'Copenhagen', body: 'Nyhavn colour, palace guards and canal swims.' },
      { heading: 'North Zealand', body: 'Hamlet’s castle and the Louisiana museum coast.' },
    ],
    experiences: [
      { heading: 'Tivoli after dark', body: 'The fairy-lit original theme park.' },
      { heading: 'Harbour swimming', body: 'Clean-water city baths, Danish-style.' },
      { heading: 'New Nordic dining', body: 'From smørrebrød lunches to world-list tasting menus.' },
    ],
    stay: [
      { heading: 'Design hotels', body: 'Danish modern done to perfection.' },
    ],
    journeyIdeas: ['Copenhagen Family Break', 'Copenhagen Food & Design', 'Denmark Summer Coast', 'Copenhagen & Southern Sweden'],
  },
  {
    slug: 'iceland', name: 'Iceland', region: 'Europe', priorityRank: 52,
    strapline: 'The land still being made.',
    blurb: 'Waterfalls, black beaches, glacier lagoons and skies that dance in winter.',
    tags: ['Nature', 'Adventure', 'Northern Lights', 'Family', 'Road Trip'],
    seasonality: { best: [6, 7, 8], good: [5, 9, 2, 3, 10], possible: [11, 12, 1, 4] },
    subDestinations: [
      { heading: 'The Golden Circle', body: 'Geysir, Gullfoss and the rift between continents.' },
      { heading: 'The South Coast', body: 'Waterfalls you walk behind and diamond-ice beaches.' },
      { heading: 'Reykjavík', body: 'The world’s most northerly capital, disproportionately cool.' },
    ],
    experiences: [
      { heading: 'Blue Lagoon & Sky Lagoon', body: 'Geothermal bathing with volcanic views.' },
      { heading: 'Glacier lagoon boats', body: 'Icebergs calving into Jökulsárlón.' },
      { heading: 'Ice-cave & aurora winters', body: 'Blue crystal caves by day, green skies by night.' },
    ],
    stay: [
      { heading: 'Countryside design lodges', body: 'Floor-to-ceiling lava-field views.' },
      { heading: 'Reykjavík boutiques', body: 'Harbour-side Nordic cool.' },
    ],
    journeyIdeas: ['Iceland Golden Circle & South Coast', 'Iceland Family Adventure', 'Northern Lights & Ice Caves', 'Luxury Iceland Road Trip'],
  },
  {
    slug: 'china', name: 'China', region: 'Asia', priorityRank: 53,
    strapline: 'The middle kingdom, wide open.',
    blurb: 'The Great Wall, terracotta armies, karst rivers and skylines from the future.',
    tags: ['Culture', 'History', 'Family', 'Food', 'Touring'],
    seasonality: { best: [4, 5, 9, 10], good: [3, 11], possible: [6, 7, 8, 12, 1, 2] },
    subDestinations: [
      { heading: 'Beijing', body: 'The Forbidden City and the Wall at Mutianyu.' },
      { heading: 'Xi’an', body: 'The Terracotta Army and Ming city walls.' },
      { heading: 'Shanghai', body: 'Bund grandeur facing Pudong’s glass forest.' },
      { heading: 'Guilin & Yangshuo', body: 'Karst peaks over the Li River.' },
    ],
    experiences: [
      { heading: 'Great Wall hikes', body: 'Restored ramparts to wild sections, crowd-free with timing.' },
      { heading: 'Terracotta Warriors', body: 'Eight thousand soldiers, each face unique.' },
      { heading: 'Li River cruising', body: 'The landscape from the twenty-yuan note.' },
      { heading: 'Dumpling trails', body: 'From soup dumplings to Peking duck, guided.' },
    ],
    stay: [
      { heading: 'Courtyard hotels in Beijing', body: 'Hutong heritage behind red doors.' },
      { heading: 'Bund-view icons', body: 'Shanghai glamour, 1930s to now.' },
    ],
    journeyIdeas: ['Beijing, Xi’an & Shanghai', 'China Family Discovery', 'China Food & Culture Journey', 'China & Hong Kong Twin-Centre'],
  },
  {
    slug: 'india', name: 'India', region: 'Asia', priorityRank: 54,
    strapline: 'Everything, everywhere, all at once.',
    blurb: 'Taj Mahal dawns, tiger jungles, Kerala backwaters and palace hotels fit for maharajas.',
    tags: ['Culture', 'Wildlife', 'Luxury', 'Wellness', 'Touring'],
    seasonality: { best: [10, 11, 12, 1, 2, 3], good: [4, 9], possible: [5, 6, 7, 8] },
    subDestinations: [
      { heading: 'The Golden Triangle', body: 'Delhi, Agra and Jaipur — the classic first circuit.' },
      { heading: 'Rajasthan', body: 'Blue cities, desert forts and palace-hotel nights.' },
      { heading: 'Kerala', body: 'Houseboat backwaters, tea hills and ayurveda.' },
      { heading: 'The national parks', body: 'Ranthambore and Bandhavgarh tiger country.' },
    ],
    experiences: [
      { heading: 'Taj Mahal at sunrise', body: 'The white marble blushing pink — worth every early alarm.' },
      { heading: 'Houseboat nights', body: 'Kerala’s palm-lined canals at walking pace.' },
      { heading: 'Tiger safaris', body: 'Dawn drives with India’s apex icon.' },
      { heading: 'Palace-hotel stays', body: 'Sleep in the maharaja’s actual palace.' },
    ],
    stay: [
      { heading: 'Heritage palaces', body: 'Udaipur and Jaipur’s converted royal residences.' },
      { heading: 'Kerala backwater villas', body: 'Waterside serenity and ayurvedic spas.' },
    ],
    journeyIdeas: ['Golden Triangle & Rajasthan', 'Kerala Backwaters & Beach', 'India Wildlife & Luxury Lodges', 'Himalayan Wellness Escape'],
  },
  {
    slug: 'nepal', name: 'Nepal', region: 'Asia', priorityRank: 55,
    strapline: 'Top of the world, feet on the ground.',
    blurb: 'Himalayan sunrises, medieval squares and treks for every level of knee.',
    tags: ['Mountains', 'Adventure', 'Culture', 'Value', 'Trekking'],
    seasonality: { best: [10, 11, 3, 4], good: [2, 5, 9, 12], possible: [1, 6, 7, 8] },
    subDestinations: [
      { heading: 'Kathmandu Valley', body: 'Durbar squares, stupas and prayer-flag hills.' },
      { heading: 'Pokhara', body: 'Lakeside calm beneath the Annapurnas.' },
      { heading: 'Chitwan', body: 'Rhinos and tigers in the lowland jungle.' },
    ],
    experiences: [
      { heading: 'Everest scenic flights', body: 'The roof of the world from a window seat.' },
      { heading: 'Poon Hill trek', body: 'The achievable Himalayan sunrise classic.' },
      { heading: 'Boudhanath at dusk', body: 'Butter lamps and circling pilgrims.' },
    ],
    stay: [
      { heading: 'Heritage boutiques in Kathmandu', body: 'Newari courtyards restored.' },
      { heading: 'Mountain-view lodges', body: 'Annapurna panoramas with hot showers.' },
    ],
    journeyIdeas: ['Kathmandu & Pokhara', 'Nepal Family Adventure', 'Himalayan Trek & Luxury Lodges', 'Nepal Culture & Wildlife'],
  },
  {
    slug: 'bhutan', name: 'Bhutan', region: 'Asia', priorityRank: 56,
    strapline: 'The kingdom of happiness.',
    blurb: 'Cliff-face monasteries, prayer-flag passes and a country that measures what matters.',
    tags: ['Culture', 'Mountains', 'Wellness', 'Luxury', 'Hiking'],
    seasonality: { best: [3, 4, 5, 10, 11], good: [9, 12], possible: [1, 2, 6, 7, 8] },
    subDestinations: [
      { heading: 'Paro', body: 'The Tiger’s Nest monastery clinging to its cliff.' },
      { heading: 'Thimphu', body: 'The capital without a single traffic light.' },
      { heading: 'Punakha', body: 'The great dzong at the river confluence.' },
    ],
    experiences: [
      { heading: 'Tiger’s Nest hike', body: 'The pilgrimage every visitor makes — worth every step.' },
      { heading: 'Festival tsechus', body: 'Masked dances in fortress courtyards.' },
      { heading: 'Hot-stone baths', body: 'River stones, herbs and mountain silence.' },
    ],
    stay: [
      { heading: 'Luxury lodge circuits', body: 'Valley-to-valley five-star pilgrimage.' },
      { heading: 'Heritage farmhouses', body: 'Family hospitality, prayer wheels at the door.' },
    ],
    journeyIdeas: ['Bhutan Valleys & Monasteries', 'Bhutan Luxury Wellness Journey', 'Bhutan Hiking & Culture', 'Bhutan & Nepal Twin-Centre'],
  },
  {
    slug: 'cambodia', name: 'Cambodia', region: 'Asia', priorityRank: 57,
    strapline: 'Temples, resilience and river life.',
    blurb: 'Angkor’s sunrise silhouette, floating villages and an island coast on the rise.',
    tags: ['Culture', 'History', 'Family', 'Beach', 'Value'],
    seasonality: { best: [11, 12, 1, 2], good: [3, 10], possible: [4, 5, 6, 7, 8, 9] },
    subDestinations: [
      { heading: 'Siem Reap & Angkor', body: 'The world’s greatest temple complex.' },
      { heading: 'Phnom Penh', body: 'Royal palaces and essential, sobering history.' },
      { heading: 'The islands', body: 'Koh Rong’s bioluminescent bays.' },
    ],
    experiences: [
      { heading: 'Angkor Wat sunrise', body: 'The towers mirrored in the lotus pond.' },
      { heading: 'Ta Prohm’s tree roots', body: 'The jungle reclaiming the temple.' },
      { heading: 'Floating villages', body: 'Tonlé Sap’s stilted water world.' },
    ],
    stay: [
      { heading: 'Siem Reap pool boutiques', body: 'Colonial-Khmer style minutes from the temples.' },
      { heading: 'Island beach bungalows', body: 'Barefoot simplicity, improving fast.' },
    ],
    journeyIdeas: ['Angkor & Phnom Penh', 'Cambodia Family Discovery', 'Cambodia & Vietnam Journey', 'Temples, Coast & Countryside'],
  },
  {
    slug: 'philippines', name: 'Philippines', region: 'Asia', priorityRank: 58,
    strapline: 'Seven thousand islands, one big welcome.',
    blurb: 'Palawan’s lagoons, whale sharks, chocolate hills and the warmest people in Asia.',
    tags: ['Islands', 'Beach', 'Diving', 'Family', 'Adventure'],
    seasonality: { best: [12, 1, 2, 3, 4], good: [5, 11], possible: [6, 7, 8, 9, 10] },
    subDestinations: [
      { heading: 'Palawan', body: 'El Nido and Coron — the lagoon postcards are real.' },
      { heading: 'Cebu & Bohol', body: 'Whale sharks, sardine runs and chocolate hills.' },
      { heading: 'Boracay', body: 'White Beach’s famous four kilometres.' },
    ],
    experiences: [
      { heading: 'El Nido island-hopping', body: 'Hidden lagoons by banca boat.' },
      { heading: 'Kayangan Lake', body: 'The clearest water you will ever swim.' },
      { heading: 'Tarsier encounters', body: 'Bohol’s pocket-sized primates.' },
    ],
    stay: [
      { heading: 'Island resorts in Palawan', body: 'Overwater luxury to eco-chic.' },
      { heading: 'Beachfront family hotels', body: 'Cebu and Boracay ease.' },
    ],
    journeyIdeas: ['Manila & Palawan', 'Philippines Island-Hopping', 'Cebu & Bohol Family Holiday', 'Luxury Palawan Escape'],
  },
  {
    slug: 'mexico', name: 'Mexico', region: 'North America', priorityRank: 59,
    strapline: 'Colour turned all the way up.',
    blurb: 'Mayan pyramids, cenote swims, Caribbean sand and food on UNESCO’s culture list.',
    tags: ['Beach', 'Culture', 'Food', 'Family', 'Adventure'],
    seasonality: { best: [11, 12, 1, 2, 3, 4], good: [5, 10], possible: [6, 7, 8, 9] },
    subDestinations: [
      { heading: 'Riviera Maya', body: 'Tulum’s clifftop ruins and cenote-dotted jungle.' },
      { heading: 'Mexico City', body: 'Museums, murals and the world’s most exciting food scene.' },
      { heading: 'Yucatán towns', body: 'Mérida’s pastel streets and Chichén Itzá.' },
    ],
    experiences: [
      { heading: 'Cenote swimming', body: 'Sunbeams in sacred sinkholes.' },
      { heading: 'Chichén Itzá early entry', body: 'The great pyramid before the buses.' },
      { heading: 'Taco omakase', body: 'Street stands to world-list dining rooms.' },
    ],
    stay: [
      { heading: 'Tulum beach boutiques', body: 'Barefoot design on white sand.' },
      { heading: 'Haciendas', body: 'Restored estates among the henequen.' },
    ],
    journeyIdeas: ['Mexico City & Riviera Maya', 'Yucatán Culture & Beach', 'Mexico Family Resort Holiday', 'Baja California Adventure'],
  },
  {
    slug: 'costa-rica', name: 'Costa Rica', region: 'Central America', priorityRank: 60,
    strapline: 'Pura vida, in the wild.',
    blurb: 'Sloths and volcanoes, cloud forests and two coastlines of surf — nature’s theme park.',
    tags: ['Nature', 'Wildlife', 'Adventure', 'Family', 'Wellness'],
    seasonality: { best: [12, 1, 2, 3, 4], good: [5, 11], possible: [6, 7, 8, 9, 10] },
    subDestinations: [
      { heading: 'Arenal', body: 'The perfect-cone volcano and its hot springs.' },
      { heading: 'Monteverde', body: 'Hanging bridges through the cloud forest.' },
      { heading: 'Manuel Antonio & the Pacific', body: 'Sloths above the beach, surf beyond.' },
    ],
    experiences: [
      { heading: 'Canopy zip lines', body: 'The sport Costa Rica invented, above the treetops.' },
      { heading: 'Wildlife night walks', body: 'Red-eyed frogs and kinkajous by torchlight.' },
      { heading: 'Hot-spring evenings', body: 'Volcano-heated rivers under the stars.' },
    ],
    stay: [
      { heading: 'Eco-lodges', body: 'Sustainability pioneers with howler-monkey alarm clocks.' },
      { heading: 'Volcano-view resorts', body: 'Arenal framed from your bath.' },
    ],
    journeyIdeas: ['Costa Rica Family Adventure', 'Rainforest, Volcano & Beach', 'Costa Rica Wildlife & Wellness', 'Luxury Eco-Lodge Journey'],
  },
];
