import type { CatalogueEntry } from './types';

/** Wave 1 — ranks 1–20. The core leisure shop window: fullest content. */
export const WAVE1: CatalogueEntry[] = [
  {
    slug: 'maldives', name: 'Maldives', region: 'Indian Ocean', priorityRank: 1, featured: true,
    strapline: 'Paradise, made easy from the UAE.',
    blurb: 'Overwater villas, house reefs and sunsets that stop time — four hours from home.',
    tags: ['Beach', 'Couples', 'Family', 'All-Inclusive', 'Honeymoon', 'Diving'],
    seasonality: { best: [11, 12, 1, 2, 3, 4], good: [5, 9, 10], possible: [6, 7, 8] },
    subDestinations: [
      { heading: 'North & South Malé Atolls', body: 'Speedboat-transfer islands 15–45 minutes from the airport — ideal for short breaks and families who want to skip the seaplane.' },
      { heading: 'Baa Atoll', body: 'UNESCO biosphere reserve famous for manta rays and whale sharks at Hanifaru Bay in the green season.' },
      { heading: 'Ari Atoll', body: 'Classic seaplane country with big house reefs, resident whale sharks and some of the best diving in the country.' },
      { heading: 'Deep south atolls', body: 'Fewer neighbours, wilder reefs and the quietest luxury in the Maldives — worth the extra domestic hop.' },
    ],
    experiences: [
      { heading: 'House-reef snorkelling', body: 'Turtles, rays and technicolour coral, metres from your villa steps.' },
      { heading: 'Sandbank picnics', body: 'A private strip of white sand, a cool box and nothing else on the horizon.' },
      { heading: 'Sunset dolphin cruises', body: 'Spinner dolphins ride the bow wave most evenings — a near guarantee.' },
      { heading: 'Overwater spa days', body: 'Treatment rooms with glass floors above the lagoon.' },
      { heading: 'Night fishing', body: 'Hand-line fishing at dusk, with the chef grilling your catch after.' },
      { heading: 'Diving with mantas', body: 'Seasonal congregations in Baa and Ari atolls for divers and snorkellers alike.' },
    ],
    stay: [
      { heading: 'Overwater villas', body: 'The postcard: steps into the lagoon, glass floor panels, sunset decks.' },
      { heading: 'Beach villas with pools', body: 'Often better value than overwater — and easier with young children.' },
      { heading: 'All-inclusive islands', body: 'Premium plans that genuinely cover excursions, fine dining and drinks.' },
    ],
    journeyIdeas: ['All-Inclusive Maldives Island Escape', 'Maldives Family Lagoon Holiday', 'Adults-Only Maldives Retreat', 'Sri Lanka & Maldives Twin-Centre'],
  },
  {
    slug: 'thailand', name: 'Thailand', region: 'Asia', priorityRank: 2, featured: true,
    strapline: 'Asia’s great all-rounder.',
    blurb: 'Limestone bays, jungle temples and street food that outclasses most restaurants.',
    tags: ['Beach', 'Family', 'Food', 'Culture', 'Value', 'Island-Hopping'],
    seasonality: { best: [11, 12, 1, 2], good: [3, 7, 8], possible: [4, 5, 6, 9, 10] },
    subDestinations: [
      { heading: 'Bangkok', body: 'Temples at dawn, rooftop bars at dusk and the best street food city on earth.' },
      { heading: 'Phuket & Khao Lak', body: 'The family workhorses: big beach resorts, kids’ clubs and easy day trips.' },
      { heading: 'Koh Samui & the Gulf', body: 'Dry when the Andaman is wet — the smart summer-holiday choice.' },
      { heading: 'Chiang Mai & the north', body: 'Hill temples, ethical elephant sanctuaries and cooler mountain air.' },
      { heading: 'Phi Phi & Krabi', body: 'The limestone postcard — longtails, lagoons and Railay’s famous cliffs.' },
    ],
    experiences: [
      { heading: 'Ethical elephant encounters', body: 'Feed and walk with rescued elephants at accredited sanctuaries near Chiang Mai.' },
      { heading: 'Street-food safaris', body: 'Guided night-market crawls from Bangkok’s Chinatown to Chiang Mai’s walking streets.' },
      { heading: 'Island-hopping by longtail', body: 'Maya Bay, Pileh Lagoon and Bamboo Island before the crowds arrive.' },
      { heading: 'Thai cooking classes', body: 'Market shopping, then curry pastes from scratch — the souvenir that lasts.' },
      { heading: 'Temple mornings', body: 'Wat Pho’s reclining Buddha and dawn alms rounds with saffron-robed monks.' },
      { heading: 'Muay Thai nights', body: 'Ringside seats at Bangkok’s stadiums for Thailand’s national sport.' },
    ],
    stay: [
      { heading: 'Beachfront family resorts', body: 'Phuket and Khao Lak lead Asia for pools, kids’ clubs and value.' },
      { heading: 'Pool villas', body: 'Private plunge pools at prices that surprise Maldives regulars.' },
      { heading: 'Boutique city hotels', body: 'Design-led riverside stays in Bangkok for the city leg.' },
    ],
    journeyIdeas: ['Phuket & Khao Lak Family Escape', 'Bangkok & Koh Samui in Style', 'Chiang Mai, Elephants & Beach', 'Thailand Island-Hopping Journey'],
  },
  {
    slug: 'mauritius', name: 'Mauritius', region: 'Indian Ocean', priorityRank: 3, featured: true,
    strapline: 'The Indian Ocean at its most generous.',
    blurb: 'Lagoon blues, volcanic peaks and resorts that do family, golf and romance equally well.',
    tags: ['Beach', 'Family', 'Golf', 'Honeymoon', 'All-Inclusive', 'Nature'],
    seasonality: { best: [5, 6, 7, 8, 9, 10, 11, 12], good: [1, 4], possible: [2, 3] },
    subDestinations: [
      { heading: 'North — Grand Baie', body: 'The liveliest coast: restaurants, boat trips and calm swimming beaches.' },
      { heading: 'East — Belle Mare', body: 'The great lagoon: kite-surfing breezes, championship golf and blue-chip resorts.' },
      { heading: 'West — Flic en Flac & Le Morne', body: 'Sunset side — dolphins at dawn, UNESCO-listed Le Morne mountain.' },
      { heading: 'South — wild coast', body: 'Cliffs, waterfalls and tea plantations where the reef breaks open.' },
    ],
    experiences: [
      { heading: 'Swim with dolphins', body: 'Early-morning encounters off Tamarin Bay on the west coast.' },
      { heading: 'Ocean-view golf', body: 'Tee off across sea inlets on some of the Indian Ocean’s best resort courses.' },
      { heading: 'Chamarel & the coloured earths', body: 'Rum tastings, waterfalls and seven-coloured dunes in the hills.' },
      { heading: 'Catamaran days', body: 'Sail to Île aux Cerfs or the northern islands with grilled lobster lunch.' },
      { heading: 'Street food in Port Louis', body: 'Dholl puri, gateaux piments and the Indian Ocean’s best market snacking.' },
      { heading: 'Sea-kayak the lagoon', body: 'Glass-calm water inside the reef, turtles beneath you.' },
    ],
    stay: [
      { heading: 'Family beach resorts', body: 'Enormous lagoon-front grounds, serious kids’ clubs, half-board value.' },
      { heading: 'Golf resorts', body: 'Stay-and-play estates with their own championship courses.' },
      { heading: 'Romantic hideaways', body: 'Adults-only wings and suite-only boutiques for honeymooners.' },
    ],
    journeyIdeas: ['Mauritius Family Resort Holiday', 'Mauritius Golf & Beach Escape', 'Romantic Mauritius for Two', 'Mauritius Adventure, Mountains & Coast'],
  },
  {
    slug: 'sri-lanka', name: 'Sri Lanka', region: 'Asia', priorityRank: 4, featured: true,
    strapline: 'A whole continent on one island.',
    blurb: 'Tea hills, leopards, ancient cities and palm-fringed surf — all within a few hours’ drive.',
    tags: ['Culture', 'Wildlife', 'Family', 'Beach', 'Touring', 'Value'],
    seasonality: { best: [12, 1, 2, 3], good: [4, 7, 8, 11], possible: [5, 6, 9, 10] },
    intro: [
      'Few places pack this much into an island you can cross in a day: eight UNESCO sites, leopard-rich national parks, tea country that looks painted, train rides through cloud forest and two coastlines that take turns having perfect weather. From the UAE it’s a four-and-a-half-hour hop — which makes Sri Lanka the easiest genuine touring destination on our map.',
      'The classic shape is a private-driver circuit — cultural triangle, hill country, safari — finished with beach days in the south. It suits families brilliantly: distances are short, hotels are characterful and the welcome is famously warm.',
    ],
    whenToTravel: [
      { heading: 'December – March', body: 'Peak season for the west and south coasts and the hill country — dry, bright and busy over Christmas.' },
      { heading: 'April – September', body: 'The east coast’s turn: Trincomalee and Arugam Bay shine while the southwest sees afternoon rain.' },
      { heading: 'Year-round touring', body: 'The cultural triangle sits between both monsoons — touring works in every month with the right routing.' },
    ],
    subDestinations: [
      { heading: 'Cultural Triangle', body: 'Sigiriya’s rock fortress, Polonnaruwa’s ruins and cave temples at Dambulla.' },
      { heading: 'Hill country', body: 'Ella, Nuwara Eliya and the world’s most beautiful train ride through the tea.' },
      { heading: 'Yala & the safari parks', body: 'The densest leopard population on earth, plus elephants by the hundred.' },
      { heading: 'South coast', body: 'Galle Fort’s lanes, whale watching at Mirissa and boutique beach stays.' },
    ],
    experiences: [
      { heading: 'Climb Sigiriya at dawn', body: 'The lion rock fortress before the heat and the queues.' },
      { heading: 'The Ella train', body: 'Hang out of a blue carriage over tea fields — the photograph everyone comes home with.' },
      { heading: 'Leopard safari in Yala', body: 'Dawn game drives with the best leopard odds in Asia.' },
      { heading: 'Tea estate lunches', body: 'Walk the plucking rows, then lunch at a planter’s bungalow.' },
      { heading: 'Whale watching at Mirissa', body: 'Blue whales — the largest animals ever — a short boat ride offshore (in season).' },
      { heading: 'Galle Fort at golden hour', body: 'Ramparts, lighthouses and gelato in the Indian Ocean’s prettiest colonial town.' },
    ],
    stay: [
      { heading: 'Boutique tea bungalows', body: 'Planters’ houses turned five-star hideaways in the hills.' },
      { heading: 'Safari camps', body: 'Tented luxury on the edge of Yala and Wilpattu.' },
      { heading: 'South-coast beach boutiques', body: 'Barefoot-chic stays between Galle and Tangalle.' },
    ],
    journeyIdeas: ['Classic Sri Lanka: Culture, Tea & Safari', 'Sri Lanka Family Adventure', 'Wildlife, Highlands & South Coast', 'Sri Lanka & Maldives Twin-Centre'],
  },
  {
    slug: 'united-kingdom', name: 'United Kingdom', region: 'Europe', priorityRank: 5, featured: true,
    strapline: 'Go home and go exploring at the same time.',
    blurb: 'London theatres, Cotswold lanes, Highland drama — the summer escape British expats already know they love.',
    tags: ['City Break', 'Family', 'Countryside', 'Culture', 'Festive', 'Self-Drive'],
    seasonality: { best: [5, 6, 7, 8, 9], good: [4, 10, 12], possible: [1, 2, 3, 11] },
    intro: [
      'For British expats in the UAE, a UK trip usually starts as a family visit — and becomes a proper holiday with a little planning. Bolt a Cotswolds cottage, a Cornish beach week or a Highlands road trip onto the London leg, and the annual pilgrimage turns into the best trip of the year.',
      'We plan the UK the way we plan anywhere else: the right base in the right village, tables booked, cars and trains arranged, and the school-holiday crowds designed around. December works too — Christmas markets, pantomimes and log fires do half the work.',
    ],
    whenToTravel: [
      { heading: 'May – September', body: 'Long evenings, garden season and every festival worth attending. July–August is school-holiday peak — book cottages early.' },
      { heading: 'December', body: 'Christmas markets, lights on Regent Street and country-house festive breaks. Cold, dark and completely magical.' },
      { heading: 'Shoulder months', body: 'April, October: half the crowds, moody light, cosy-pub weather.' },
    ],
    subDestinations: [
      { heading: 'London', body: 'Theatre, museums and the world’s best free attractions — the anchor of every UK trip.' },
      { heading: 'The Cotswolds', body: 'Honey-stone villages, farm shops and gastropubs an easy drive west of London.' },
      { heading: 'Cornwall & Devon', body: 'Surf beaches, harbour towns and cream teas — England’s family summer at its best.' },
      { heading: 'Scotland', body: 'Edinburgh’s festivals, Highland lochs and single malts (see our dedicated Scotland golf trips too).' },
      { heading: 'The Lake District', body: 'England’s mountain country: lake steamers, fell walks and literary villages.' },
    ],
    experiences: [
      { heading: 'West End theatre nights', body: 'Matinee and dinner, planned around the shows worth flying for.' },
      { heading: 'Country-house weekends', body: 'Croquet lawns, tasting menus and spas in converted stately homes.' },
      { heading: 'Coastal path walks', body: 'Cornwall’s clifftops between beach days — pasty at the halfway point.' },
      { heading: 'Highland road trips', body: 'Glencoe, Skye and the North Coast 500 in a comfortable self-drive loop.' },
      { heading: 'Football pilgrimages', body: 'Match tickets and stadium tours arranged around your fixture list.' },
      { heading: 'Christmas markets', body: 'Bath, Edinburgh and York in full festive dress.' },
    ],
    stay: [
      { heading: 'Cotswold cottages', body: 'Self-catering character for families — Aga included.' },
      { heading: 'London townhouse hotels', body: 'Boutique bases in Marylebone, Chelsea and Covent Garden.' },
      { heading: 'Country-house hotels', body: 'The great British weekend: gardens, dogs welcome, serious kitchens.' },
    ],
    journeyIdeas: ['London & the Cotswolds', 'Scotland: Edinburgh, Highlands & Islands', 'Cornwall & Devon Family Summer', 'London, Bath & the English Countryside'],
  },
  {
    slug: 'japan', name: 'Japan', region: 'Asia', priorityRank: 6, featured: true,
    strapline: 'Unique culture, stunning scenery.',
    blurb: 'Temples and bullet trains, ryokans and neon nights — the trip that changes how you travel.',
    tags: ['Culture', 'Food', 'Family', 'Ski', 'City Break', 'Touring'],
    seasonality: { best: [3, 4, 10, 11], good: [5, 9, 12, 1, 2], possible: [6, 7, 8] },
    subDestinations: [
      { heading: 'Tokyo', body: 'Neon crossings, teamLab, sushi counters and the world’s most polite megacity.' },
      { heading: 'Kyoto & Nara', body: 'Ten thousand torii gates, golden pavilions and bowing deer.' },
      { heading: 'Hakone & Fuji', body: 'Onsen towns and lake crossings beneath the perfect volcano.' },
      { heading: 'Osaka & Hiroshima', body: 'Street-food capital and the peace park every visitor should see.' },
      { heading: 'Hokkaido', body: 'Champagne powder in winter, lavender fields and seafood in summer.' },
    ],
    experiences: [
      { heading: 'Ryokan & kaiseki night', body: 'Tatami rooms, hot-spring baths and a dinner of twenty tiny masterpieces.' },
      { heading: 'Bullet-train touring', body: 'Country-crossing at 300km/h with a bento on your knee.' },
      { heading: 'Fushimi Inari at dawn', body: 'The vermilion gate tunnels before the crowds arrive.' },
      { heading: 'Sushi omakase', body: 'Counter seats where the chef decides — book months ahead, worth every yen.' },
      { heading: 'Snow monkeys & powder', body: 'Nagano’s bathing macaques and Japan’s legendary ski resorts.' },
      { heading: 'teamLab and pop culture', body: 'Digital art oceans, Ghibli, Akihabara — Japan for the kids (and you).' },
    ],
    stay: [
      { heading: 'Traditional ryokan', body: 'At least one night — it is Japan distilled.' },
      { heading: 'City design hotels', body: 'Compact, immaculate and brilliantly located in Tokyo and Kyoto.' },
      { heading: 'Ski-in Hokkaido lodges', body: 'Niseko and Furano for the powder pilgrimage.' },
    ],
    journeyIdeas: ['Tokyo, Kyoto & Osaka First-Timer', 'Japan with Children', 'Hokkaido Ski & Snow Adventure', 'Japan in Cherry Blossom Season'],
  },
  {
    slug: 'vietnam', name: 'Vietnam', region: 'Asia', priorityRank: 7, featured: true,
    strapline: 'The fastest-rising star in Asia.',
    blurb: 'Lantern-lit old towns, emerald bays and the best-value food scene on the continent.',
    tags: ['Culture', 'Food', 'Beach', 'Family', 'Value', 'Touring'],
    seasonality: { best: [2, 3, 4, 10, 11], good: [1, 5, 12], possible: [6, 7, 8, 9] },
    intro: [
      'Vietnam runs the length of a coastline as long as California’s, and changes completely along the way: misty rice terraces and French-colonial boulevards in the north, imperial cities and lantern-lit lanes in the centre, Mekong markets and island beaches in the south. UAE travellers have discovered it in force — value is exceptional and the food alone justifies the flight.',
      'The classic route runs north to south: Hanoi’s old quarter, a night among Halong Bay’s limestone towers, tailor-made suits and river lanterns in Hoi An, then Saigon’s buzz and a Phu Quoc beach finish.',
    ],
    whenToTravel: [
      { heading: 'February – April', body: 'The sweet spot countrywide: dry in the south, blossoming in the north, beach weather in the centre.' },
      { heading: 'October – December', body: 'Crisp northern touring and Phu Quoc’s dry season — ideal for a winter-sun beach finish.' },
      { heading: 'Summer', body: 'Hot and green; the central coast (Danang, Hoi An) is at its beach best June–August.' },
    ],
    subDestinations: [
      { heading: 'Hanoi & the north', body: 'Old-quarter energy, egg coffee and Sapa’s stitched rice terraces.' },
      { heading: 'Halong Bay', body: 'Two thousand limestone islands — spend the night aboard, it changes everything.' },
      { heading: 'Hoi An & Hue', body: 'Lantern town and imperial citadel, linked by the Hai Van Pass.' },
      { heading: 'Ho Chi Minh City & Mekong', body: 'Rooftop bars, war history and floating markets in the delta.' },
      { heading: 'Phu Quoc', body: 'Vietnam’s beach island — resorts, sunsets and seafood shacks.' },
    ],
    experiences: [
      { heading: 'Overnight on Halong Bay', body: 'Kayak between karsts at dusk, breakfast on deck in the mist.' },
      { heading: 'Hoi An by lantern light', body: 'Riverside lanterns, tailor fittings and the best banh mi in Vietnam.' },
      { heading: 'Street-food crawls', body: 'Pho at dawn, bun cha at lunch — eat where the locals queue.' },
      { heading: 'Motorbike the Hai Van Pass', body: 'Top Gear’s favourite road, by Vespa sidecar or comfortable car.' },
      { heading: 'Mekong Delta days', body: 'Sampans through coconut canals and floating-market mornings.' },
      { heading: 'Cooking classes in Hoi An', body: 'Market baskets, herb gardens and your own spring rolls.' },
    ],
    stay: [
      { heading: 'Colonial grande dames', body: 'Storied hotels in Hanoi and Saigon that wear their history beautifully.' },
      { heading: 'Hoi An boutiques', body: 'Riverside courtyards a bicycle ride from town and beach.' },
      { heading: 'Phu Quoc beach resorts', body: 'Five-star sunsets at four-star prices.' },
    ],
    journeyIdeas: ['Vietnam North to South', 'Hanoi, Halong & Hoi An', 'Vietnam Family Discovery', 'Vietnam & Phu Quoc Beach Escape'],
  },
  {
    slug: 'greece', name: 'Greece', region: 'Europe', priorityRank: 8, featured: true,
    strapline: 'Islands, myths and very long lunches.',
    blurb: 'Whitewashed villages, family beach resorts and history you can walk through barefoot.',
    tags: ['Beach', 'Islands', 'Family', 'Couples', 'Culture', 'Villas'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8], possible: [11, 3, 12, 1, 2] },
    intro: [
      'Greece is the easiest Mediterranean holiday to love: two hundred inhabited islands, an alphabet of beaches, tavernas that treat lunch as the day’s main event, and ruins that turn every ferry ride into a history lesson. For UAE-based families it is a natural summer base — and shoulder-season Greece, warm and half-empty, is the connoisseur’s pick.',
      'The art is matching traveller to island: Santorini and Mykonos for the drama, Crete and Rhodes for family firepower, Naxos and Paros for barefoot authenticity, the Peloponnese for road-trippers who want Greece without a ferry at all.',
    ],
    whenToTravel: [
      { heading: 'May – June & September – October', body: 'Warm seas, open tavernas, no crush — the best of Greece.' },
      { heading: 'July – August', body: 'Full summer: buzzing, hot, family-holiday prime. Book villas by February.' },
      { heading: 'Winter', body: 'Athens works year-round as a culture city break.' },
    ],
    subDestinations: [
      { heading: 'Athens', body: 'The Acropolis at opening time, then Plaka lanes and rooftop dinners.' },
      { heading: 'Santorini', body: 'Caldera sunsets and cave hotels — the honeymoon postcard.' },
      { heading: 'Crete', body: 'Big, generous island: palaces, gorges, pink-sand beaches and serious food.' },
      { heading: 'Mykonos & the Cyclades', body: 'Glamour, windmills and island-hopping ferry loops.' },
      { heading: 'The Peloponnese', body: 'Olympia, Nafplio and wild beaches — Greece by hire car.' },
    ],
    experiences: [
      { heading: 'Caldera sunset sailing', body: 'Catamaran, grilled dinner aboard, Santorini glowing above.' },
      { heading: 'Taverna table for the afternoon', body: 'Grilled octopus, cold assyrtiko, sea at your toes.' },
      { heading: 'Acropolis & museum morning', body: 'The Parthenon before the heat with a guide who makes it live.' },
      { heading: 'Island-hop the Cyclades', body: 'Three islands, one ferry pass, endlessly photogenic harbours.' },
      { heading: 'Samaria Gorge hike', body: 'Crete’s great canyon walk, finishing with a swim.' },
      { heading: 'Cooking with yiayia', body: 'Village cooking classes where grandma corrects your folding.' },
    ],
    stay: [
      { heading: 'Family beach resorts', body: 'Crete and Rhodes lead: waterparks, kids’ clubs, half-board ease.' },
      { heading: 'Cave suites', body: 'Santorini’s carved-in hotels with plunge pools over the caldera.' },
      { heading: 'Private villas', body: 'Pool, cook on request and your own olive trees — best value in June and September.' },
    ],
    journeyIdeas: ['Athens & Cyclades Island-Hopping', 'Crete Family Beach Holiday', 'Mykonos & Santorini for Two', 'Peloponnese Road Trip & Coast'],
  },
  {
    slug: 'turkey', name: 'Türkiye', region: 'Europe / Asia', priorityRank: 9, featured: true,
    strapline: 'Two continents, one extraordinary country.',
    blurb: 'Istanbul’s skyline, Cappadocia’s balloons, turquoise-coast gulets and serious all-inclusive value.',
    tags: ['Culture', 'Beach', 'Family', 'Golf', 'All-Inclusive', 'City Break'],
    seasonality: { best: [4, 5, 6, 9, 10], good: [3, 7, 8, 11], possible: [12, 1, 2] },
    subDestinations: [
      { heading: 'Istanbul', body: 'Hagia Sophia, the Grand Bazaar and ferries between continents.' },
      { heading: 'Cappadocia', body: 'Balloon-filled dawns over fairy chimneys and cave hotels.' },
      { heading: 'Bodrum & the Aegean', body: 'Chic marinas, gulet cruises and beach clubs.' },
      { heading: 'Antalya & Belek', body: 'The family and golf powerhouse: all-inclusive resorts and championship fairways.' },
    ],
    experiences: [
      { heading: 'Balloon over Cappadocia', body: 'A hundred balloons at sunrise — travel’s great alarm call.' },
      { heading: 'Bosphorus by boat', body: 'Palaces and waterside mansions between Europe and Asia.' },
      { heading: 'Gulet cruising', body: 'Private wooden yachts along the Turquoise Coast, swimming stops on demand.' },
      { heading: 'Hammam ritual', body: 'Marble, steam and the scrub of your life in a 400-year-old bathhouse.' },
      { heading: 'Grand Bazaar treasure hunt', body: 'Four thousand shops, one guide, zero tourist traps.' },
      { heading: 'Ephesus day', body: 'Rome’s greatest eastern city, marble streets intact.' },
    ],
    stay: [
      { heading: 'Cave hotels', body: 'Cappadocia’s carved suites with valley-view terraces.' },
      { heading: 'Ultra all-inclusive resorts', body: 'Belek and Antalya set the world standard for families.' },
      { heading: 'Bosphorus-view boutiques', body: 'Istanbul stays where the ferries drift past your window.' },
    ],
    journeyIdeas: ['Istanbul & Cappadocia', 'Bodrum Luxury Beach Escape', 'Antalya Family All-Inclusive', 'Türkiye Coast & Culture Journey'],
  },
  {
    slug: 'france', name: 'France', region: 'Europe', priorityRank: 10, featured: true,
    strapline: 'The world’s most visited country, for every good reason.',
    blurb: 'Paris and Provence, Riviera glamour, Alpine summers and Disneyland for the win.',
    tags: ['City Break', 'Family', 'Food', 'Couples', 'Ski', 'Road Trip'],
    seasonality: { best: [5, 6, 9], good: [4, 7, 8, 10, 12], possible: [1, 2, 3, 11] },
    intro: [
      'France barely needs an introduction — which is exactly why it rewards proper planning. Beyond the Paris essentials lie lavender-striped Provence, Riviera coves, château country, Alpine lakes that fix a Gulf summer instantly, and the small matter of Disneyland for the under-tens. Direct flights from the UAE make even a long weekend viable.',
      'We build France as combinations: Paris plus Provence by TGV, Riviera beach with hilltop-village lunches, Alps in summer for cool air and cable cars. Rail does the linking beautifully.',
    ],
    whenToTravel: [
      { heading: 'May – June & September', body: 'Café terraces, warm sea, lavender (late June) and no August crush.' },
      { heading: 'July – August', body: 'Riviera and Alps in full swing — the classic summer escape.' },
      { heading: 'December', body: 'Paris in lights, Alsace Christmas markets, first snow in the Alps.' },
    ],
    subDestinations: [
      { heading: 'Paris', body: 'Museums, pâtisseries and river evenings — always the right answer.' },
      { heading: 'Provence & Côte d’Azur', body: 'Hilltop villages, markets and the Mediterranean’s most famous coastline.' },
      { heading: 'The Alps', body: 'Chamonix and Annecy: summer hiking, lake swimming, winter skiing.' },
      { heading: 'Loire & Bordeaux', body: 'Châteaux, vineyards and very good lunches between them.' },
      { heading: 'Disneyland Paris', body: 'Two parks, direct TGV access, military-grade planning by us.' },
    ],
    experiences: [
      { heading: 'Louvre & Musée d’Orsay, skip-the-line', body: 'The masterpieces without the queue mathematics.' },
      { heading: 'Market-to-table Provence', body: 'Shop the morning market, cook it with a chef by noon.' },
      { heading: 'Riviera coast drives', body: 'Èze, Saint-Paul-de-Vence and the Corniche roads in a convertible.' },
      { heading: 'Mont Blanc cable cars', body: 'The Aiguille du Midi at 3,842m — Europe’s greatest balcony.' },
      { heading: 'Champagne cellar day', body: 'Épernay’s houses by private car, flutes included.' },
      { heading: 'Seine dinner cruise', body: 'Paris doing its evening show from the water.' },
    ],
    stay: [
      { heading: 'Paris boutiques', body: 'Left Bank charm or Marais cool — location is everything and we know the map.' },
      { heading: 'Provence mas & villas', body: 'Stone farmhouses with pools among the vines.' },
      { heading: 'Alpine lodges', body: 'Lake Annecy and Chamonix bases for summer cool or winter snow.' },
    ],
    journeyIdeas: ['Paris & the French Riviera', 'Paris with Disneyland', 'French Alps Summer Adventure', 'Provence & Côte d’Azur Road Trip'],
  },
  {
    slug: 'italy', name: 'Italy', region: 'Europe', priorityRank: 11, featured: true,
    strapline: 'Life, perfected.',
    blurb: 'Renaissance cities, lemon-grove coastlines, lake palazzos and the world’s favourite food.',
    tags: ['Culture', 'Food', 'Couples', 'Family', 'Lakes', 'Coast'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8], possible: [11, 12, 1, 2, 3] },
    intro: [
      'Italy is less a destination than a lifetime project — Rome’s layered centuries, Florence’s impossible art density, Venice at dawn, the Amalfi Coast’s vertical villages, lakes that seduced Clooney and Como alike, and Tuscany, which needs no adjective. Every region eats differently, and every region is convinced it eats best. They’re all right.',
      'First-timers should take the classic triangle — Rome, Florence, Venice by rail. Returners head for the lakes, Puglia’s trulli towns or a Tuscan villa week where the itinerary is lunch.',
    ],
    whenToTravel: [
      { heading: 'May – June & September – October', body: 'Golden light, open terraces, swimmable seas — Italy at its most generous.' },
      { heading: 'July – August', body: 'Coast and lakes thrive; cities run hot. Villa season peaks.' },
      { heading: 'Winter', body: 'Rome and Florence without queues; opera season; Dolomites snow.' },
    ],
    subDestinations: [
      { heading: 'Rome', body: 'The Colosseum, the Vatican and carbonara arguments — eternal indeed.' },
      { heading: 'Florence & Tuscany', body: 'Uffizi mornings, hill-town afternoons, vineyard evenings.' },
      { heading: 'Venice', body: 'Get lost on purpose; it’s the only way it works.' },
      { heading: 'Amalfi Coast & Capri', body: 'Cliff roads, lemon terraces and boat days.' },
      { heading: 'The Lakes', body: 'Como and Garda: belle-époque villas, mountain backdrops.' },
    ],
    experiences: [
      { heading: 'Vatican at opening', body: 'The Sistine Chapel in near-silence, with a guide worth their fee.' },
      { heading: 'Tuscan cooking day', body: 'Pasta from flour and eggs, lunch in the vines after.' },
      { heading: 'Amalfi by boat', body: 'Skip the coast road traffic — arrive at Positano from the sea.' },
      { heading: 'Gondola-free Venice', body: 'Backwater bacari crawls and a traghetto crossing for pennies.' },
      { heading: 'Como villa gardens', body: 'Balbianello and Carlotta by private launch.' },
      { heading: 'Truffle hunting', body: 'Autumn in Piedmont with a hunter and his suspiciously smug dog.' },
    ],
    stay: [
      { heading: 'Tuscan villas', body: 'Pools, olive groves and space for three generations.' },
      { heading: 'Amalfi cliff hotels', body: 'Terraced icons where breakfast comes with vertigo.' },
      { heading: 'City palazzo boutiques', body: 'Frescoed ceilings a stroll from the sights.' },
    ],
    journeyIdeas: ['Rome, Florence & Venice', 'Amalfi Coast & Capri', 'Lake Como & the Italian Lakes', 'Tuscany Family Villa Holiday'],
  },
  {
    slug: 'spain', name: 'Spain', region: 'Europe', priorityRank: 12, featured: true,
    strapline: 'Fiesta, siesta and everything between.',
    blurb: 'Gaudí’s Barcelona, Andalusian palaces, island beaches and tapas as a way of life.',
    tags: ['Beach', 'City Break', 'Family', 'Culture', 'Islands', 'Food'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8], possible: [11, 12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Barcelona', body: 'Gaudí, beaches and the best food city on the Med.' },
      { heading: 'Madrid & the centre', body: 'Golden-triangle art, tapas crawls and day-trip Toledo.' },
      { heading: 'Andalusia', body: 'Seville, Granada’s Alhambra and white villages in the hills.' },
      { heading: 'Mallorca & the Balearics', body: 'Family coves, mountain villages and Ibiza’s two faces.' },
      { heading: 'Costa del Sol', body: 'Reliable sun, golf by the mile and family resort machinery.' },
    ],
    experiences: [
      { heading: 'Sagrada Família with a Gaudí expert', body: 'The basilica explained makes it ten times taller.' },
      { heading: 'Alhambra at first entry', body: 'The Nasrid Palaces before the day’s heat and hordes.' },
      { heading: 'Tapas like a local', body: 'Stand at the bar, order in rounds, follow the ham.' },
      { heading: 'Flamenco in Seville', body: 'A peña performance, not a dinner show.' },
      { heading: 'Tramuntana coast drives', body: 'Mallorca’s Deià and Sóller — the island’s beautiful side.' },
      { heading: 'Paella masterclass in Valencia', body: 'In its birthplace, over orange wood.' },
    ],
    stay: [
      { heading: 'Paradores', body: 'Castles and convents turned characterful state-run hotels.' },
      { heading: 'Balearic beach resorts', body: 'Family firepower on Mallorca’s best bays.' },
      { heading: 'Andalusian palacio boutiques', body: 'Courtyards, orange trees and rooftop plunge pools.' },
    ],
    journeyIdeas: ['Barcelona & Mallorca', 'Madrid, Seville & Andalusia', 'Costa del Sol Family Holiday', 'Ibiza & Formentera for Couples'],
  },
  {
    slug: 'bali', name: 'Indonesia (Bali)', region: 'Asia', priorityRank: 13, featured: true,
    strapline: 'The island that resets you.',
    blurb: 'Jungle villas, rice-terrace mornings, surf sunsets and wellness done properly.',
    tags: ['Beach', 'Wellness', 'Family', 'Villas', 'Culture', 'Value'],
    seasonality: { best: [4, 5, 6, 7, 8, 9], good: [3, 10], possible: [11, 12, 1, 2] },
    intro: [
      'Bali runs on a different clock. Mornings start with offerings on doorsteps and mist over rice terraces; days drift between temple courtyards, waterfall swims and beach clubs; evenings end with grilled fish on the sand. UAE travellers increasingly treat it as the long-stay summer answer: villas with private pools cost less than a hotel room elsewhere, and the island genuinely suits families, honeymooners and the wellness-inclined all at once.',
      'The trick is pairing areas: cultural Ubud in the jungle interior first, then a coast — polished Nusa Dua and Uluwatu’s clifftops for resorts, Canggu for surf-and-smoothie energy, or the Nusa islands for a barefoot finish.',
    ],
    whenToTravel: [
      { heading: 'April – October', body: 'The dry season: blue skies, low humidity, perfect pool-villa weather — peak July–August.' },
      { heading: 'November – March', body: 'Green season: short heavy showers, lush landscapes, sharp value. Fine for spa-and-villa trips.' },
    ],
    subDestinations: [
      { heading: 'Ubud', body: 'Rice terraces, monkey forest, yoga barns and Bali’s cultural heart.' },
      { heading: 'Uluwatu & Nusa Dua', body: 'Clifftop temples, big-name resorts and the island’s best swimming beaches.' },
      { heading: 'Canggu & Seminyak', body: 'Surf schools, beach clubs and the brunch capital of Asia.' },
      { heading: 'Nusa Islands & Komodo', body: 'Manta rays, dragon treks and blue water a boat ride away.' },
    ],
    experiences: [
      { heading: 'Sunrise at Lempuyang', body: 'The gates of heaven with Agung floating behind.' },
      { heading: 'Rice-terrace walks', body: 'Tegallalang and Jatiluwih on foot, coconut at the halfway warung.' },
      { heading: 'Waterfall circuit', body: 'Sekumpul and Nung Nung — bring swimwear, expect spray.' },
      { heading: 'Balinese spa days', body: 'Flower baths and four-hand massages at jungle spas.' },
      { heading: 'Surf lessons at Canggu', body: 'Stand up on day one on Bali’s forgiving beach breaks.' },
      { heading: 'Uluwatu kecak at sunset', body: 'Fire dance on a clifftop as the sun drops into the Indian Ocean.' },
    ],
    stay: [
      { heading: 'Private pool villas', body: 'Bali’s superpower — family compounds and honeymoon hideaways alike.' },
      { heading: 'Jungle lodges in Ubud', body: 'Valley-edge infinity pools with gibbon soundtracks.' },
      { heading: 'Clifftop resorts', body: 'Uluwatu’s dramatic five-stars above the surf.' },
    ],
    journeyIdeas: ['Bali: Ubud & Beach', 'Bali Family Villa Holiday', 'Bali Wellness & Slow Travel', 'Bali & Komodo Adventure'],
  },
  {
    slug: 'canada', name: 'Canada', region: 'North America', priorityRank: 14, featured: true,
    strapline: 'Big nature, easy cities, endless summer daylight.',
    blurb: 'Turquoise Rockies lakes, whale-rich coasts and road trips built for school holidays.',
    tags: ['Nature', 'Family', 'Self-Drive', 'City Break', 'Wildlife', 'Ski'],
    seasonality: { best: [6, 7, 8, 9], good: [5, 10, 12, 1, 2], possible: [3, 4, 11] },
    intro: [
      'Canada is the great school-holiday country: long summer days, drive-anywhere infrastructure, moose-and-bear wildlife and lakes coloured like toothpaste adverts. A UAE summer swap for Banff’s 22-degree afternoons is an easy sell — and the cities (Vancouver, Toronto, Montreal) are among the world’s most livable to visit.',
      'The classic first trip pairs the Rockies self-drive with Vancouver; the eastern alternative links Toronto, Niagara and French-flavoured Montreal and Quebec City. Winter flips the script: powder at Whistler and frozen-lake romance in Banff.',
    ],
    whenToTravel: [
      { heading: 'June – September', body: 'The Rockies’ golden window: hiking, lakes and wildlife all open for business.' },
      { heading: 'September – October', body: 'Autumn colour in the east — maple country in full fire.' },
      { heading: 'December – March', body: 'Whistler and Banff ski season; Quebec’s winter carnival.' },
    ],
    subDestinations: [
      { heading: 'Banff & the Rockies', body: 'Lake Louise, Moraine and the Icefields Parkway — earth’s best road trip.' },
      { heading: 'Vancouver & Whistler', body: 'Mountains meeting ocean, with North America’s premier ski resort up the road.' },
      { heading: 'Toronto & Niagara', body: 'Skyline mornings, thundering falls by afternoon.' },
      { heading: 'Montreal & Quebec City', body: 'French joie de vivre, cobbles and bagels vs croissants.' },
    ],
    experiences: [
      { heading: 'Drive the Icefields Parkway', body: '230km of glaciers and impossibly blue lakes between Banff and Jasper.' },
      { heading: 'Whale watching in BC', body: 'Orcas off Vancouver Island from May to October.' },
      { heading: 'Canoe Lake Louise', body: 'The turquoise postcard, paddled at 8am before the crowds.' },
      { heading: 'Niagara by boat', body: 'Ponchos on, into the mist beneath the Horseshoe Falls.' },
      { heading: 'Bear spotting', body: 'Grizzlies at dawn with certified guides in the Rockies foothills.' },
      { heading: 'Poutine & maple everything', body: 'Quebec’s comfort food canon, unapologetically.' },
    ],
    stay: [
      { heading: 'Fairmont castle hotels', body: 'The railway-era icons at Lake Louise, Banff and Quebec.' },
      { heading: 'Lakeside lodges', body: 'Cabin evenings, canoe mornings.' },
      { heading: 'City design hotels', body: 'Walkable bases in Vancouver, Toronto and Montreal.' },
    ],
    journeyIdeas: ['Toronto, Niagara & Montreal', 'Canadian Rockies Self-Drive', 'Vancouver & Whistler Family Adventure', 'Eastern Canada Autumn Colours'],
  },
  {
    slug: 'australia', name: 'Australia', region: 'Oceania', priorityRank: 15, featured: true,
    strapline: 'Worth every hour of the flight.',
    blurb: 'Harbour-city glamour, reef snorkelling, rainforest walks and roads made for the long way round.',
    tags: ['Family', 'Nature', 'Beach', 'City Break', 'Self-Drive', 'Wildlife'],
    seasonality: { best: [10, 11, 12, 1, 2, 3], good: [4, 5, 9], possible: [6, 7, 8] },
    intro: [
      'Australia rewards the UAE’s long school holidays like nowhere else: one flight, no jet-lag-inducing connections, and a country that packs the Great Barrier Reef, ancient rainforest, wine valleys and the world’s most photogenic harbour city into a single (very large) island. Expat family links make it a natural VFR-plus-holiday destination too.',
      'First trips usually run Sydney → Queensland: harbour icons, then reef and rainforest from Cairns or the Whitsundays. Melbourne adds laneway culture and the Great Ocean Road; the west offers quokkas, Ningaloo and sunsets over the Indian Ocean pointing straight back at Dubai.',
    ],
    whenToTravel: [
      { heading: 'October – March', body: 'Australian summer: beach season in Sydney and Melbourne (UAE winter escape).' },
      { heading: 'April – September', body: 'The dry season up north — prime reef, rainforest and Outback months.' },
    ],
    subDestinations: [
      { heading: 'Sydney', body: 'Opera House sails, harbour ferries and Bondi to Bronte at sunrise.' },
      { heading: 'Queensland', body: 'The Reef, the Daintree and Whitsunday sailing — Australia’s tropics.' },
      { heading: 'Melbourne & Victoria', body: 'Coffee-obsessed laneways and the Great Ocean Road’s Twelve Apostles.' },
      { heading: 'Western Australia', body: 'Perth, Rottnest’s quokkas and Ningaloo’s whale sharks.' },
      { heading: 'The Red Centre', body: 'Uluru at dawn — spiritual heart, desert silence.' },
    ],
    experiences: [
      { heading: 'Snorkel the Great Barrier Reef', body: 'Outer-reef pontoons and coral gardens from Cairns or Port Douglas.' },
      { heading: 'BridgeClimb Sydney', body: 'Sunrise on top of the Harbour Bridge arch.' },
      { heading: 'Great Ocean Road drive', body: 'Koalas at Kennett River, Apostles at golden hour.' },
      { heading: 'Whitsundays under sail', body: 'Whitehaven’s swirling silica sands from the deck.' },
      { heading: 'Daintree rainforest walks', body: 'The world’s oldest rainforest, cassowaries included.' },
      { heading: 'Uluru field of light', body: 'Fifty thousand solar stems under the desert stars.' },
    ],
    stay: [
      { heading: 'Harbour-view hotels', body: 'Sydney rooms where the Opera House is your television.' },
      { heading: 'Reef island resorts', body: 'Hamilton, Hayman and Lizard for barefoot luxury.' },
      { heading: 'Rainforest lodges', body: 'Treehouse sleeps in the Daintree canopy.' },
    ],
    journeyIdeas: ['Sydney, Reef & Rainforest', 'Melbourne & Great Ocean Road', 'Australia Family Highlights', 'Perth & Western Australia Escape'],
  },
  {
    slug: 'united-states', name: 'United States', region: 'North America', priorityRank: 16, featured: true,
    strapline: 'The great American everything.',
    blurb: 'Theme-park summers, canyon road trips, city icons and coast-to-coast variety.',
    tags: ['Family', 'City Break', 'Road Trip', 'Theme Parks', 'Nature', 'Shopping'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8, 11, 12], possible: [1, 2, 3] },
    subDestinations: [
      { heading: 'New York', body: 'The skyline, the shows, the bagels — still the greatest city break.' },
      { heading: 'Orlando & Florida', body: 'Disney and Universal at full throttle, beaches to recover on.' },
      { heading: 'California', body: 'Pacific Coast Highway, national parks and Hollywood mythology.' },
      { heading: 'The Southwest', body: 'Grand Canyon, Monument Valley and Vegas as the absurd base camp.' },
      { heading: 'New England', body: 'Boston history and October’s riot of fall colour.' },
    ],
    experiences: [
      { heading: 'Broadway nights', body: 'Orchestra seats booked long before you fly.' },
      { heading: 'Disney done right', body: 'Lightning Lanes, dining plans and park-day strategy handled by us.' },
      { heading: 'Pacific Coast Highway', body: 'Big Sur bends with the roof down.' },
      { heading: 'Grand Canyon sunrise', body: 'South Rim first light — no photograph prepares you.' },
      { heading: 'NBA & NFL games', body: 'Tickets and hospitality for the bucket-list fixtures.' },
      { heading: 'Yosemite valley walks', body: 'El Capitan and Half Dome from the meadow floor.' },
    ],
    stay: [
      { heading: 'Manhattan icons', body: 'Central Park views and doormen who remember your name.' },
      { heading: 'Theme-park resorts', body: 'On-property perks that transform Orlando logistics.' },
      { heading: 'National-park lodges', body: 'Sleep inside the view at the Grand Canyon and Yosemite.' },
    ],
    journeyIdeas: ['New York & Orlando Family Holiday', 'California Coast Road Trip', 'New York, Washington & Boston', 'West Coast National Parks Adventure'],
  },
  {
    slug: 'seychelles', name: 'Seychelles', region: 'Indian Ocean', priorityRank: 17, featured: true,
    strapline: 'The Indian Ocean’s wild side.',
    blurb: 'Granite-boulder beaches, giant tortoises and island-hopping by ferry — four hours from the Gulf.',
    tags: ['Beach', 'Honeymoon', 'Island-Hopping', 'Nature', 'Couples', 'Family'],
    seasonality: { best: [4, 5, 10, 11], good: [3, 6, 9, 12], possible: [1, 2, 7, 8] },
    intro: [
      'Where the Maldives is lagoon-flat perfection, the Seychelles is drama: granite boulders the size of houses tumbling into jade water, jungle ridges behind every bay, and beaches — Anse Source d’Argent, Anse Lazio — that top world lists on rotation. Direct four-hour flights and no visa make it a favourite UAE winter escape.',
      'Unlike one-island destinations, the Seychelles is built for hopping: Mahé’s mountains and capital, Praslin’s primeval Vallée de Mai, and car-free La Digue where bicycles and ox carts set the pace.',
    ],
    whenToTravel: [
      { heading: 'April – May & October – November', body: 'The calm between trade winds: glassy seas, best visibility, ideal beach weather.' },
      { heading: 'December – March', body: 'Warmer and greener with brief showers — still fine beach season.' },
      { heading: 'June – September', body: 'Breezier southeast trades — great for sailing, cooler evenings.' },
    ],
    subDestinations: [
      { heading: 'Mahé', body: 'Mountain drives, Victoria’s creole market and sixty-plus beaches.' },
      { heading: 'Praslin', body: 'Home of the coco de mer and Anse Lazio’s famous curve.' },
      { heading: 'La Digue', body: 'Bicycles, granite coves and the world’s most photographed beach.' },
      { heading: 'Private islands', body: 'One-resort islands for the full castaway fantasy.' },
    ],
    experiences: [
      { heading: 'Anse Source d’Argent at low tide', body: 'Wade the shallows between the granite giants.' },
      { heading: 'Vallée de Mai walk', body: 'A prehistoric palm forest — the “original Eden”.' },
      { heading: 'Giant tortoise encounters', body: 'Century-old Aldabra giants roaming free on Curieuse.' },
      { heading: 'Island-hop by ferry', body: 'Three islands in one holiday with an hour’s crossing between.' },
      { heading: 'Creole table d’hôte', body: 'Octopus curry and breadfruit at family-run tables.' },
      { heading: 'Snorkel St Pierre islet', body: 'Fish-soup water around a postcard granite outcrop.' },
    ],
    stay: [
      { heading: 'Hillside villas on Mahé', body: 'Infinity pools hanging over the bays.' },
      { heading: 'Beachfront boutiques on La Digue', body: 'Barefoot, bicycle-distance from everything.' },
      { heading: 'Private-island resorts', body: 'North, Frégate, Denis — conservation-led castaway luxury.' },
    ],
    journeyIdeas: ['Mahé & Praslin Island Escape', 'Seychelles Honeymoon', 'Seychelles Family Beach Holiday', 'Seychelles Island-Hopping Adventure'],
  },
  {
    slug: 'switzerland', name: 'Switzerland', region: 'Europe', priorityRank: 18, featured: true,
    strapline: 'The heart of the Alps.',
    blurb: 'Glacier peaks, mirror lakes and the world’s most scenic railways — summer cooling perfected.',
    tags: ['Nature', 'Family', 'Rail', 'Ski', 'Lakes', 'Luxury'],
    seasonality: { best: [6, 7, 8, 9], good: [5, 12, 1, 2, 3], possible: [4, 10, 11] },
    subDestinations: [
      { heading: 'Lucerne & Central Switzerland', body: 'Chapel Bridge, paddle steamers and Pilatus’s golden round trip.' },
      { heading: 'Interlaken & Jungfrau', body: 'Adventure capital beneath the Eiger — and the Top of Europe railway.' },
      { heading: 'Zermatt', body: 'Car-free village life under the Matterhorn.' },
      { heading: 'Lake Geneva & Montreux', body: 'Riviera palms, vineyard terraces and the GoldenPass line.' },
    ],
    experiences: [
      { heading: 'Glacier Express', body: 'Eight hours of panoramic windows between Zermatt and St Moritz.' },
      { heading: 'Jungfraujoch', body: 'Europe’s highest railway station at 3,454m — snow in July.' },
      { heading: 'Lake swims & steamers', body: 'Brienz’s turquoise, Geneva’s belle-époque boats.' },
      { heading: 'Alpine coaster & zip lines', body: 'Grindelwald First’s cliff walk and family adrenaline menu.' },
      { heading: 'Cheese & chocolate trails', body: 'Gruyères and Maison Cailler in one very rich day.' },
      { heading: 'Matterhorn sunrise', body: 'Gornergrat’s viewing deck as the peak catches fire.' },
    ],
    stay: [
      { heading: 'Grand belle-époque hotels', body: 'Palace hotels with lake terraces and 150-year guestbooks.' },
      { heading: 'Car-free mountain villages', body: 'Zermatt, Wengen and Mürren — arrive by train, breathe.' },
      { heading: 'Family apartments', body: 'Self-catering bases with the Alps outside the window.' },
    ],
    journeyIdeas: ['Swiss Alps by Rail', 'Switzerland Family Summer', 'Lucerne, Interlaken & Zermatt', 'Luxury Swiss Ski Escape'],
  },
  {
    slug: 'south-korea', name: 'South Korea', region: 'Asia', priorityRank: 19, featured: true,
    strapline: 'Tradition at full speed.',
    blurb: 'Palace mornings, K-culture nights, volcanic islands and food you’ll dream about.',
    tags: ['Culture', 'Food', 'City Break', 'Family', 'Design', 'Winter'],
    seasonality: { best: [4, 5, 9, 10, 11], good: [3, 6, 12], possible: [1, 2, 7, 8] },
    intro: [
      'Seoul does something rare: palaces where kings walked five hundred years ago sit a subway stop from neon gaming districts and the studios driving global pop culture. Add street food that turned fried chicken into an art form, autumn mountains on the city’s doorstep and Jeju’s volcanic beaches, and it’s clear why UAE winter demand keeps climbing.',
      'A first trip pairs Seoul with coastal Busan by high-speed rail; families add Everland and the character cafés; food-lovers simply follow the queues.',
    ],
    whenToTravel: [
      { heading: 'April – May', body: 'Cherry blossom and spring festivals — Seoul at its prettiest.' },
      { heading: 'September – November', body: 'Crisp days and blazing autumn foliage in the palace gardens and national parks.' },
      { heading: 'December – February', body: 'Cold, clear and atmospheric: ski resorts, street-food steam and festive lights.' },
    ],
    subDestinations: [
      { heading: 'Seoul', body: 'Gyeongbokgung’s changing of the guard to Gangnam’s glow — one city, five centuries.' },
      { heading: 'Busan', body: 'Beaches, cliff temples and Korea’s great seafood market.' },
      { heading: 'Jeju Island', body: 'Volcanic craters, waterfalls and haenyeo free-diving grandmothers.' },
      { heading: 'Gyeongju', body: 'The “museum without walls” — royal tombs and gilded temples.' },
    ],
    experiences: [
      { heading: 'Hanbok palace mornings', body: 'Rent traditional dress and walk Gyeongbokgung like a drama lead.' },
      { heading: 'Korean BBQ & banchan', body: 'Grill-at-table feasts with a local who knows the cuts.' },
      { heading: 'K-pop & K-drama trails', body: 'Studios, filming spots and fan cafés for the family’s superfan.' },
      { heading: 'Jjimjilbang spa night', body: 'Korea’s bathhouse culture — saunas, sleep rooms and sweet rice drink.' },
      { heading: 'Temple stay', body: 'Dawn bells and monastic meals in a mountain monastery.' },
      { heading: 'DMZ day tour', body: 'The world’s strangest border, an hour from Seoul.' },
    ],
    stay: [
      { heading: 'Design hotels in Seoul', body: 'Myeongdong and Gangnam bases with skyline views.' },
      { heading: 'Hanok guesthouses', body: 'Traditional courtyard houses in Bukchon’s lanes.' },
      { heading: 'Jeju beach resorts', body: 'Volcanic-coast family stays.' },
    ],
    journeyIdeas: ['Seoul & Busan', 'South Korea Family Discovery', 'Seoul, Jeju & the Coast', 'Korea Food, Culture & Design'],
  },
  {
    slug: 'south-africa', name: 'South Africa', region: 'Africa', priorityRank: 20, featured: true,
    strapline: 'A world in one country.',
    blurb: 'Big Five dawns, Cape Town glamour, wineland lunches and the Garden Route’s open road.',
    tags: ['Safari', 'Wildlife', 'Food & Wine', 'Family', 'Self-Drive', 'Golf'],
    seasonality: { best: [10, 11, 2, 3, 4], good: [5, 9, 12, 1], possible: [6, 7, 8] },
    intro: [
      'Nowhere else strings together a leopard sighting at dawn, a world-top-ten lunch in the winelands and an Atlantic sunset from Table Mountain — in the same day if you push it. South Africa is the great-value luxury destination: the rand makes five-star lodges and tasting menus startlingly accessible from the UAE.',
      'The classic first journey pairs Cape Town and the winelands with a Kruger-area safari; families add the Garden Route’s whales, ostriches and beach towns in a gentle self-drive.',
    ],
    whenToTravel: [
      { heading: 'May – September', body: 'Prime safari: dry bush, animals at the waterholes. Cape Town’s green winter.' },
      { heading: 'October – March', body: 'Cape Town’s summer — beach days, long winery lunches. Green-season safari with baby animals.' },
      { heading: 'June – November', body: 'Whale season in Hermanus — southern rights from the clifftop.' },
    ],
    subDestinations: [
      { heading: 'Cape Town', body: 'Table Mountain, Camps Bay sunsets and the Cape Peninsula’s penguins.' },
      { heading: 'The Winelands', body: 'Stellenbosch and Franschhoek: Cape Dutch estates and serious cellars.' },
      { heading: 'Kruger & Sabi Sands', body: 'The Big Five heartland — private reserves for guaranteed quality.' },
      { heading: 'The Garden Route', body: 'Knysna lagoons, Plettenberg beaches and forest walks by hire car.' },
    ],
    experiences: [
      { heading: 'Big Five game drives', body: 'Dawn and dusk with rangers who read the bush like a newspaper.' },
      { heading: 'Table Mountain cableway', body: 'Up for sunset, city lights on the way down.' },
      { heading: 'Franschhoek wine tram', body: 'Hop-off tastings through the prettiest valley in wine.' },
      { heading: 'Penguins at Boulders Beach', body: 'African penguins at swimming distance.' },
      { heading: 'Whale watching, Hermanus', body: 'The world’s best land-based whale viewing (Jun–Nov).' },
      { heading: 'Cape Point drive', body: 'Chapman’s Peak bends to the meeting of two oceans.' },
    ],
    stay: [
      { heading: 'Private safari lodges', body: 'Sabi Sands suites with plunge pools and leopards past the deck.' },
      { heading: 'Cape Town boutiques', body: 'V&A waterfront glamour or Camps Bay beach houses.' },
      { heading: 'Wineland manor houses', body: 'Cape Dutch estates among the vines.' },
    ],
    journeyIdeas: ['Cape Town, Winelands & Safari', 'South Africa Family Adventure', 'Garden Route Self-Drive', 'Luxury Safari & Cape Escape'],
  },
];
