import type { CatalogueEntry } from './types';

/** Wave 2 — ranks 21–40. Full pages with solid launch content. */
export const WAVE2: CatalogueEntry[] = [
  {
    slug: 'portugal', name: 'Portugal', region: 'Europe', priorityRank: 21,
    strapline: 'Europe’s west edge, at its warmest.',
    blurb: 'Lisbon’s tiled hills, Algarve gold and Atlantic light — with Europe’s most reliable winter golf.',
    tags: ['Beach', 'Golf', 'City Break', 'Family', 'Food', 'Villas'],
    seasonality: { best: [4, 5, 6, 9, 10], good: [3, 7, 8, 11], possible: [12, 1, 2] },
    subDestinations: [
      { heading: 'Lisbon', body: 'Tram 28, pastéis de nata and miradouro sunsets over the Tagus.' },
      { heading: 'The Algarve', body: 'Golden cliffs, family resorts and forty golf courses within an hour.' },
      { heading: 'Porto & the Douro', body: 'Port cellars and terraced river valleys by boat or vintage train.' },
      { heading: 'Madeira', body: 'Levada walks, cloud forests and year-round spring.' },
    ],
    experiences: [
      { heading: 'Pastel de nata masterclass', body: 'Blistered custard tarts from a Lisbon pastry chef.' },
      { heading: 'Benagil caves by kayak', body: 'The Algarve’s famous sea-cave dome from water level.' },
      { heading: 'Douro valley tastings', body: 'Quinta terraces where port is born.' },
      { heading: 'Fado nights in Alfama', body: 'Portugal’s blues, sung close enough to feel.' },
    ],
    stay: [
      { heading: 'Cliff-top Algarve resorts', body: 'Family pools above the golden coves.' },
      { heading: 'Lisbon boutique palácios', body: 'Azulejo-tiled townhouses in Alfama and Chiado.' },
      { heading: 'Douro wine quintas', body: 'Sleep on the terraces among the vines.' },
    ],
    journeyIdeas: ['Lisbon & Porto', 'Algarve Family Beach Holiday', 'Portugal Golf Escape', 'Madeira Nature & Wellness'],
  },
  {
    slug: 'georgia', name: 'Georgia', region: 'Caucasus', priorityRank: 22,
    strapline: 'A short flight, a world away.',
    blurb: 'Ancient monasteries, mountain silhouettes and legendary hospitality — three hours from the Gulf.',
    tags: ['Culture', 'Mountains', 'Food & Wine', 'Family', 'Value', 'Ski'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8, 12, 1, 2], possible: [3, 11] },
    subDestinations: [
      { heading: 'Tbilisi', body: 'Balconied old town, sulphur baths and a wine bar on every corner.' },
      { heading: 'Kazbegi', body: 'Gergeti Trinity Church beneath a 5,000m peak.' },
      { heading: 'Kakheti', body: 'Wine country — qvevri cellars and supra feasts.' },
      { heading: 'Gudauri', body: 'Big-mountain skiing at small-resort prices.' },
    ],
    experiences: [
      { heading: 'Supra feast with a tamada', body: 'Georgia’s legendary toasting dinner.' },
      { heading: 'Qvevri wine tastings', body: '8,000 years of winemaking in buried clay.' },
      { heading: 'Sulphur bath scrub', body: 'Tbilisi’s domed bathhouses, the proper way.' },
      { heading: 'Military Highway drive', body: 'Ananuri fortress to the Kazbegi viewpoints.' },
    ],
    stay: [
      { heading: 'Old-town boutiques', body: 'Balconied houses above Tbilisi’s lanes.' },
      { heading: 'Mountain lodges', body: 'Kazbegi stays facing the big peaks.' },
      { heading: 'Wine-estate guesthouses', body: 'Sleep at the cellar door in Kakheti.' },
    ],
    journeyIdeas: ['Tbilisi & Kakheti Wine Country', 'Georgia Family Mountain Escape', 'Kazbegi & Caucasus Road Trip', 'Gudauri Ski Weekend'],
  },
  {
    slug: 'oman', name: 'Oman', region: 'Middle East', priorityRank: 23,
    strapline: 'The Gulf’s best-kept secret, next door.',
    blurb: 'Fjord-like khors, green monsoon hills, desert forts and turtle beaches — a drive or a short hop away.',
    tags: ['Nature', 'Self-Drive', 'Family', 'Adventure', 'Culture', 'Short Break'],
    seasonality: { best: [10, 11, 12, 1, 2, 3], good: [4, 9, 7, 8], possible: [5, 6] },
    subDestinations: [
      { heading: 'Muscat', body: 'Corniche elegance, the Grand Mosque and souk evenings.' },
      { heading: 'Jabal Akhdar & Jabal Shams', body: 'Cliff-edge resorts on the “Green Mountain” — 15° cooler than the coast.' },
      { heading: 'Salalah', body: 'The khareef monsoon turns Dhofar green each summer — the region’s strangest, loveliest secret.' },
      { heading: 'Musandam', body: 'Arabia’s fjords: dhow days with dolphins off the bow.' },
    ],
    experiences: [
      { heading: 'Wadi swims', body: 'Emerald pools at Wadi Shab and Bani Khalid.' },
      { heading: 'Turtle nesting at Ras Al Jinz', body: 'Green turtles laying by moonlight.' },
      { heading: 'Empty Quarter dunes', body: 'Sunset in the world’s largest sand sea.' },
      { heading: 'Dhow through Musandam', body: 'Fjord cruising with snorkel stops.' },
    ],
    stay: [
      { heading: 'Clifftop mountain resorts', body: 'Jabal Akhdar’s canyon-edge infinity pools.' },
      { heading: 'Beach resorts in Muscat', body: 'Corniche five-stars between mountains and sea.' },
      { heading: 'Desert camps', body: 'Sharqiya Sands under untouched stars.' },
    ],
    journeyIdeas: ['Muscat & Jabal Akhdar', 'Salalah Khareef Escape', 'Oman Desert, Mountains & Coast', 'Luxury Musandam Weekend'],
  },
  {
    slug: 'malaysia', name: 'Malaysia', region: 'Asia', priorityRank: 24,
    strapline: 'Truly Asia, minus the crowds.',
    blurb: 'Skyline cities, tea highlands, jungle wildlife and island beaches — remarkable value throughout.',
    tags: ['Family', 'Beach', 'Food', 'Nature', 'City Break', 'Value'],
    seasonality: { best: [2, 3, 4, 5, 6, 7, 8], good: [1, 9], possible: [10, 11, 12] },
    subDestinations: [
      { heading: 'Kuala Lumpur', body: 'Petronas Towers, street-food alleys and mega-mall monsoons.' },
      { heading: 'Langkawi', body: 'Duty-free island of rainforest skywalks and sunset beaches.' },
      { heading: 'Penang', body: 'George Town’s street art and Asia’s best hawker food.' },
      { heading: 'Borneo', body: 'Orangutans, river safaris and Kinabalu’s summit.' },
    ],
    experiences: [
      { heading: 'Hawker-stall crawl in Penang', body: 'Char kway teow to cendol with a local guide.' },
      { heading: 'Orangutans at Sepilok', body: 'Rehabilitated apes swinging back to the wild.' },
      { heading: 'Langkawi mangrove safari', body: 'Eagles, caves and limestone karsts by boat.' },
      { heading: 'Cameron Highlands tea walks', body: 'Rolling plantations and scones at altitude.' },
    ],
    stay: [
      { heading: 'Langkawi beach resorts', body: 'Rainforest-backed five-stars at honest prices.' },
      { heading: 'George Town heritage stays', body: 'Shophouse boutiques among the murals.' },
      { heading: 'Borneo jungle lodges', body: 'River-edge decks with wild orangutan odds.' },
    ],
    journeyIdeas: ['Kuala Lumpur & Langkawi', 'Malaysia Family Adventure', 'Borneo Wildlife & Beach', 'Penang Food & Heritage Escape'],
  },
  {
    slug: 'singapore', name: 'Singapore', region: 'Asia', priorityRank: 25,
    strapline: 'The city of the future, today.',
    blurb: 'Supertrees, hawker stars and the world’s best airport — the perfect family city or stopover.',
    tags: ['City Break', 'Family', 'Food', 'Stopover', 'Design', 'Shopping'],
    seasonality: { best: [2, 3, 4, 5, 6, 7], good: [1, 8, 9, 10], possible: [11, 12] },
    subDestinations: [
      { heading: 'Marina Bay', body: 'The skyline icons: Gardens by the Bay, the Sands and the light shows.' },
      { heading: 'Sentosa', body: 'Universal Studios, aquariums and beach clubs on the resort island.' },
      { heading: 'Chinatown & Little India', body: 'Temple incense, wet markets and Michelin-starred hawker stalls.' },
    ],
    experiences: [
      { heading: 'Supertrees after dark', body: 'The Garden Rhapsody light show, free and unmissable.' },
      { heading: 'Hawker-centre feasting', body: 'Chicken rice and chilli crab where the stars are stuck to stalls.' },
      { heading: 'Night Safari', body: 'The world’s first nocturnal zoo — leopards by moonlight.' },
      { heading: 'Rooftop infinity swims', body: 'That pool, that skyline.' },
    ],
    stay: [
      { heading: 'Marina Bay icons', body: 'Skyline suites above the light shows.' },
      { heading: 'Sentosa family resorts', body: 'Theme-park-distance stays with pools to spare.' },
      { heading: 'Heritage shophouse boutiques', body: 'Peranakan character in Chinatown and Katong.' },
    ],
    journeyIdeas: ['Singapore Family City Break', 'Singapore & Sentosa', 'Singapore & Bali Twin-Centre', 'Singapore Food & Design Weekend'],
  },
  {
    slug: 'austria', name: 'Austria', region: 'Europe', priorityRank: 26,
    strapline: 'Waltzes, peaks and perfect lakes.',
    blurb: 'Imperial Vienna, Sound-of-Music Salzburg, swimmable alpine lakes and world-class skiing.',
    tags: ['City Break', 'Lakes', 'Ski', 'Family', 'Culture', 'Festive'],
    seasonality: { best: [6, 7, 8, 12], good: [5, 9, 1, 2, 3], possible: [4, 10, 11] },
    subDestinations: [
      { heading: 'Vienna', body: 'Coffee houses, Klimt and concert halls in the imperial capital.' },
      { heading: 'Salzburg', body: 'Mozart’s baroque stage set beneath a clifftop fortress.' },
      { heading: 'Salzkammergut lakes', body: 'Hallstatt and Wolfgangsee — emerald water, postcard villages.' },
      { heading: 'Tyrol', body: 'Innsbruck and the great ski valleys.' },
    ],
    experiences: [
      { heading: 'Concert in a palace', body: 'Mozart and Strauss where they premiered.' },
      { heading: 'Lake swims & steamers', body: 'Wooden boats and Alpine water in high summer.' },
      { heading: 'Christmas markets', body: 'Vienna and Salzburg in glühwein-scented December dress.' },
      { heading: 'Sound of Music trails', body: 'The hills are alive; the kids will forgive you.' },
    ],
    stay: [
      { heading: 'Ringstrasse grand hotels', body: 'Vienna’s chandeliered classics.' },
      { heading: 'Lakeside family inns', body: 'Salzkammergut charm with a jetty.' },
      { heading: 'Ski-in Tyrol lodges', body: 'St Anton and Kitzbühel comfort.' },
    ],
    journeyIdeas: ['Vienna & Salzburg', 'Austrian Lakes Family Summer', 'Tyrol Ski Holiday', 'Christmas Markets by Rail'],
  },
  {
    slug: 'netherlands', name: 'Netherlands', region: 'Europe', priorityRank: 27,
    strapline: 'Canals, tulips and two-wheeled freedom.',
    blurb: 'Amsterdam’s golden-age canals, spring tulip fields and Europe’s most family-friendly cities.',
    tags: ['City Break', 'Family', 'Culture', 'Cycling', 'Spring', 'Festive'],
    seasonality: { best: [4, 5, 6, 9], good: [7, 8, 12], possible: [1, 2, 3, 10, 11] },
    subDestinations: [
      { heading: 'Amsterdam', body: 'Rijksmuseum, canal rings and brown-café evenings.' },
      { heading: 'Keukenhof & tulip country', body: 'Seven million bulbs in bloom each spring.' },
      { heading: 'Rotterdam & The Hague', body: 'Cutting-edge architecture and Vermeer by the sea.' },
    ],
    experiences: [
      { heading: 'Canal cruising at dusk', body: 'The golden-age houses lit from the water.' },
      { heading: 'Van Gogh & Rijksmuseum', body: 'Timed entries, no queues, all the masters.' },
      { heading: 'Cycle like the Dutch', body: 'Guided rides through Vondelpark and beyond.' },
      { heading: 'Zaanse Schans windmills', body: 'Clogs, cheese and turning sails.' },
    ],
    stay: [
      { heading: 'Canal-house boutiques', body: 'Sleep inside the 17th century, gables and all.' },
      { heading: 'Family apartment hotels', body: 'Space and kitchens in museum-quarter locations.' },
    ],
    journeyIdeas: ['Amsterdam & Dutch Countryside', 'Netherlands Family Spring Break', 'Amsterdam, Rotterdam & The Hague', 'Festive Amsterdam & Winter Villages'],
  },
  {
    slug: 'finland', name: 'Finland', region: 'Europe', priorityRank: 28,
    strapline: 'Where winter becomes magic.',
    blurb: 'Santa’s Lapland, glass igloos under the aurora and the happiest capital in Europe.',
    tags: ['Winter', 'Family', 'Northern Lights', 'Festive', 'Nature', 'Adventure'],
    seasonality: { best: [12, 1, 2, 3], good: [6, 7, 8, 11], possible: [4, 5, 9, 10] },
    subDestinations: [
      { heading: 'Rovaniemi', body: 'Santa’s official hometown on the Arctic Circle.' },
      { heading: 'Saariselkä & Levi', body: 'Deep-Lapland resorts for auroras and husky trails.' },
      { heading: 'Helsinki', body: 'Design district, island fortresses and sauna culture.' },
    ],
    experiences: [
      { heading: 'Meet Santa properly', body: 'The real Arctic Circle version — handled with wonder intact.' },
      { heading: 'Husky sled mornings', body: 'Your own team through silent snow forest.' },
      { heading: 'Aurora hunting', body: 'Snowmobile or sleigh to dark-sky viewpoints.' },
      { heading: 'Ice sauna & lake plunge', body: 'The Finnish contrast therapy, gasp included.' },
    ],
    stay: [
      { heading: 'Glass igloos', body: 'Watch for the lights without leaving bed.' },
      { heading: 'Log cabins with saunas', body: 'Fireplaces, snow outside, family space inside.' },
    ],
    journeyIdeas: ['Lapland Family Christmas', 'Finnish Lapland Glass-Igloo Escape', 'Helsinki & Arctic Circle', 'Finland Winter Adventure'],
  },
  {
    slug: 'germany', name: 'Germany', region: 'Europe', priorityRank: 29,
    strapline: 'Castles, Christmas and the open autobahn.',
    blurb: 'Fairy-tale Bavaria, big-hearted cities and Europe’s best Christmas markets.',
    tags: ['City Break', 'Family', 'Festive', 'Road Trip', 'Castles', 'Culture'],
    seasonality: { best: [5, 6, 9, 12], good: [4, 7, 8, 10], possible: [1, 2, 3, 11] },
    subDestinations: [
      { heading: 'Munich & Bavaria', body: 'Beer gardens, Alpine lakes and Neuschwanstein’s towers.' },
      { heading: 'Berlin', body: 'History at every corner, art in every basement.' },
      { heading: 'The Black Forest', body: 'Cuckoo-clock villages, spa towns and cake with a region named after it.' },
      { heading: 'The Rhine & Mosel', body: 'Castle-topped river bends and steep riesling vineyards.' },
    ],
    experiences: [
      { heading: 'Neuschwanstein at opening', body: 'The fairy-tale castle before the coaches.' },
      { heading: 'Christmas market crawl', body: 'Nuremberg, Munich and Cologne in one festive rail loop.' },
      { heading: 'Beer-garden afternoons', body: 'Chestnut shade, pretzels, litre glasses.' },
      { heading: 'Europa-Park days', body: 'Germany’s answer to Disney — and arguably better rides.' },
    ],
    stay: [
      { heading: 'Bavarian gasthofs', body: 'Family-run inns with featherbeds and enormous breakfasts.' },
      { heading: 'City design hotels', body: 'Berlin and Munich cool, walkably placed.' },
      { heading: 'Black Forest spa resorts', body: 'Baden-Baden’s thermal grandeur.' },
    ],
    journeyIdeas: ['Munich & Bavarian Alps', 'Berlin & Hamburg City Pair', 'Germany Christmas Markets', 'Black Forest Family Road Trip'],
  },
  {
    slug: 'croatia', name: 'Croatia', region: 'Europe', priorityRank: 30,
    strapline: 'The Mediterranean as it once was.',
    blurb: 'Walled cities, a thousand islands and sailing waters made for lazy summers.',
    tags: ['Beach', 'Islands', 'Sailing', 'Family', 'History', 'Food'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8], possible: [11, 12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Dubrovnik', body: 'The marble-streeted “Pearl of the Adriatic” and its city walls.' },
      { heading: 'Split & Hvar', body: 'Roman palace living and the sunniest island in Europe.' },
      { heading: 'Istria', body: 'Truffle hills and Venetian harbour towns in the north.' },
      { heading: 'Plitvice & Krka', body: 'Waterfall national parks in impossible shades of blue.' },
    ],
    experiences: [
      { heading: 'Walk Dubrovnik’s walls', body: 'First entry, before the ships — King’s Landing to yourself.' },
      { heading: 'Island-hop by catamaran', body: 'Hvar, Vis and the Blue Cave in one shining day.' },
      { heading: 'Truffle hunting in Istria', body: 'Autumn’s white gold with hunter and hound.' },
      { heading: 'Peka dinners', body: 'Lamb and octopus baked under the iron bell.' },
    ],
    stay: [
      { heading: 'Old-town heritage stays', body: 'Sleep inside Diocletian’s palace walls.' },
      { heading: 'Island family hotels', body: 'Pine-shaded bays on Hvar and Brač.' },
      { heading: 'Private sail charters', body: 'Skippered yachts as floating villas.' },
    ],
    journeyIdeas: ['Dubrovnik & Split', 'Croatian Island-Hopping', 'Istria Food & Coast', 'Croatia Family Sailing Holiday'],
  },
  {
    slug: 'montenegro', name: 'Montenegro', region: 'Europe', priorityRank: 31,
    strapline: 'Small country, enormous drama.',
    blurb: 'The Bay of Kotor’s fjord-like curves, black mountains and an Adriatic riviera in miniature.',
    tags: ['Coast', 'Mountains', 'Couples', 'Road Trip', 'Luxury', 'Value'],
    seasonality: { best: [5, 6, 9], good: [4, 7, 8, 10], possible: [11, 12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Bay of Kotor', body: 'Venetian towns beneath vertical mountains — Europe’s southern fjord.' },
      { heading: 'Budva Riviera', body: 'Beach towns and the island-hotel icon of Sveti Stefan.' },
      { heading: 'Durmitor', body: 'Black-pine national park, Tara canyon rafting.' },
    ],
    experiences: [
      { heading: 'Kotor’s ladder of steps', body: '1,350 steps to the fortress — sunrise pays for the climb.' },
      { heading: 'Bay cruise to Our Lady of the Rocks', body: 'The bell-towered islet in the fjord.' },
      { heading: 'Tara canyon rafting', body: 'Europe’s deepest gorge, glacier-green water.' },
      { heading: 'Lovćen serpentines', body: 'The 25-hairpin road with the Bay unrolling below.' },
    ],
    stay: [
      { heading: 'Bayfront palazzo boutiques', body: 'Stone captains’ houses on the waterline.' },
      { heading: 'Riviera resorts', body: 'Adriatic five-stars at half-Riviera prices.' },
    ],
    journeyIdeas: ['Bay of Kotor Escape', 'Montenegro Coast & Mountains', 'Luxury Adriatic Road Trip', 'Montenegro Family Summer'],
  },
  {
    slug: 'azerbaijan', name: 'Azerbaijan', region: 'Caucasus', priorityRank: 32,
    strapline: 'Where the Silk Road meets the space age.',
    blurb: 'Flame Towers and medieval lanes, mud volcanoes and mountain villages — a three-hour hop away.',
    tags: ['City Break', 'Culture', 'Mountains', 'Family', 'Value', 'Short Break'],
    seasonality: { best: [4, 5, 6, 9, 10], good: [3, 7, 8, 11], possible: [12, 1, 2] },
    subDestinations: [
      { heading: 'Baku', body: 'UNESCO old city wrapped in flame-shaped glass.' },
      { heading: 'Gabala & the mountains', body: 'Cable cars, lakes and cool-air resorts.' },
      { heading: 'Sheki', body: 'Silk Road khan’s palace and caravanserai sleeps.' },
    ],
    experiences: [
      { heading: 'Old City & Flame Towers', body: 'Two Bakus in one evening walk.' },
      { heading: 'Mud volcanoes & Gobustan', body: 'Bubbling moonscape and 10,000-year-old rock art.' },
      { heading: 'Fire temple & burning hillside', body: 'Yanar Dag’s eternal flames.' },
      { heading: 'Mountain-village day trips', body: 'Khinalug’s stone houses above the clouds.' },
    ],
    stay: [
      { heading: 'Boulevard five-stars', body: 'Caspian-front glamour at gentle prices.' },
      { heading: 'Mountain resorts', body: 'Gabala’s alpine-style escapes.' },
    ],
    journeyIdeas: ['Baku City Break', 'Baku & Caucasus Mountains', 'Azerbaijan Family Discovery', 'Food, Fire & Silk Road Journey'],
  },
  {
    slug: 'armenia', name: 'Armenia', region: 'Caucasus', priorityRank: 33,
    strapline: 'The world’s first Christian nation, still singing.',
    blurb: 'Monasteries on cliff edges, Ararat views, brandy cellars and mountain hospitality.',
    tags: ['Culture', 'Mountains', 'History', 'Food', 'Value', 'Short Break'],
    seasonality: { best: [5, 6, 9, 10], good: [4, 7, 8], possible: [11, 12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Yerevan', body: 'Café-filled pink-stone capital with Ararat on the skyline.' },
      { heading: 'Lake Sevan', body: 'The high-altitude “Armenian sea” and its peninsula monastery.' },
      { heading: 'Dilijan', body: 'Forested “little Switzerland” of spa air and monastic trails.' },
    ],
    experiences: [
      { heading: 'Geghard & Garni', body: 'Rock-hewn monastery and Roman temple in one valley.' },
      { heading: 'Tatev by cable car', body: 'The world’s longest reversible ropeway to a clifftop monastery.' },
      { heading: 'Brandy tasting', body: 'Ararat cellars — Churchill’s favourite.' },
      { heading: 'Lavash baking', body: 'UNESCO-listed flatbread from the tonir oven.' },
    ],
    stay: [
      { heading: 'Yerevan boutiques', body: 'Design stays off Republic Square.' },
      { heading: 'Dilijan forest resorts', body: 'Spa retreats among the oaks.' },
    ],
    journeyIdeas: ['Yerevan & Lake Sevan', 'Armenia Culture & Monasteries', 'Armenia Family Mountain Escape', 'Wine, Food & History Road Trip'],
  },
  {
    slug: 'czech-republic', name: 'Czech Republic', region: 'Europe', priorityRank: 34,
    strapline: 'A fairy tale with better beer.',
    blurb: 'Prague’s hundred spires, castle towns and Christmas markets straight from a snow globe.',
    tags: ['City Break', 'Culture', 'Festive', 'Couples', 'History', 'Value'],
    seasonality: { best: [5, 6, 9, 12], good: [4, 7, 8, 10], possible: [1, 2, 3, 11] },
    subDestinations: [
      { heading: 'Prague', body: 'Charles Bridge dawns, castle sunsets and cellar pubs between.' },
      { heading: 'Český Krumlov', body: 'A riverside miniature of towers and lanes.' },
      { heading: 'Bohemian spa towns', body: 'Karlovy Vary’s colonnades and curative springs.' },
    ],
    experiences: [
      { heading: 'Charles Bridge at dawn', body: 'Thirty statues, no crowds, golden light.' },
      { heading: 'Castle & Golden Lane', body: 'The world’s largest castle complex, properly told.' },
      { heading: 'Beer-hall evenings', body: 'Pilsner at the source, goulash on the side.' },
      { heading: 'Vltava river cruises', body: 'The spires from the water at sunset.' },
    ],
    stay: [
      { heading: 'Old Town boutiques', body: 'Gothic beams and cobbled views.' },
      { heading: 'Castle-district hideaways', body: 'Quiet lanes above the river.' },
    ],
    journeyIdeas: ['Prague Long Weekend', 'Prague Christmas Markets', 'Prague & Český Krumlov', 'Prague, Vienna & Budapest'],
  },
  {
    slug: 'morocco', name: 'Morocco', region: 'Africa', priorityRank: 35,
    strapline: 'Africa’s doorstep, a world entire.',
    blurb: 'Medina mazes, Atlas passes, Sahara camps and riads built around orange trees.',
    tags: ['Culture', 'Desert', 'Adventure', 'Food', 'Family', 'Riads'],
    seasonality: { best: [3, 4, 5, 10, 11], good: [2, 9, 12], possible: [1, 6, 7, 8] },
    subDestinations: [
      { heading: 'Marrakech', body: 'Jemaa el-Fnaa’s nightly circus and souk-lane treasure hunts.' },
      { heading: 'The Atlas Mountains', body: 'Berber villages and mule trails an hour from the medina.' },
      { heading: 'The Sahara', body: 'Erg Chebbi’s dunes by camel, camps beneath shooting stars.' },
      { heading: 'Essaouira & the coast', body: 'Blue boats, gnawa music and Atlantic breezes.' },
    ],
    experiences: [
      { heading: 'Sunset over Jemaa el-Fnaa', body: 'Storytellers, drummers and smoke from a rooftop café.' },
      { heading: 'Desert camp night', body: 'Dune sunset, firelit dinner, dawn from the ridge.' },
      { heading: 'Hammam & rhassoul ritual', body: 'Centuries-old bathing done beautifully.' },
      { heading: 'Tagine masterclass', body: 'Souk shopping, then slow-cooked perfection.' },
    ],
    stay: [
      { heading: 'Marrakech riads', body: 'Courtyard fountains and rooftop breakfasts in the medina.' },
      { heading: 'Atlas kasbah lodges', body: 'Mountain views, Berber hospitality.' },
      { heading: 'Luxury desert camps', body: 'Proper beds under canvas among the dunes.' },
    ],
    journeyIdeas: ['Marrakech & Atlas Mountains', 'Morocco Desert & Kasbahs', 'Marrakech Family Adventure', 'Morocco Coast, Food & Culture'],
  },
  {
    slug: 'egypt', name: 'Egypt', region: 'Africa / Middle East', priorityRank: 36,
    strapline: 'Five thousand years, four hours away.',
    blurb: 'Pyramids at dawn, Nile sails at dusk and Red Sea reefs in between.',
    tags: ['History', 'Culture', 'Family', 'Beach', 'Cruise', 'Value'],
    seasonality: { best: [10, 11, 12, 1, 2, 3], good: [4, 9], possible: [5, 6, 7, 8] },
    subDestinations: [
      { heading: 'Cairo & Giza', body: 'The last ancient wonder and the Grand Egyptian Museum.' },
      { heading: 'Luxor & Aswan', body: 'Karnak, the Valley of the Kings and felucca sunsets.' },
      { heading: 'The Red Sea', body: 'El Gouna and Sahl Hasheesh: reefs, kite lagoons, family resorts.' },
    ],
    experiences: [
      { heading: 'Pyramids with an Egyptologist', body: 'The Giza plateau decoded, camels optional.' },
      { heading: 'Nile cruising', body: 'Temples by day, deck chairs by golden hour.' },
      { heading: 'Valley of the Kings', body: 'Tutankhamun’s tomb and painted corridors underground.' },
      { heading: 'Red Sea snorkelling', body: 'Coral walls minutes from your beach.' },
    ],
    stay: [
      { heading: 'Pyramid-view classics', body: 'Mena House’s garden views of Giza.' },
      { heading: 'Nile cruise boats', body: 'Five-star floating hotels between Luxor and Aswan.' },
      { heading: 'Red Sea family resorts', body: 'Lagoon pools and house reefs.' },
    ],
    journeyIdeas: ['Cairo & Nile Cruise', 'Luxor, Aswan & the Nile', 'Red Sea Family Resort', 'Egypt Culture & Beach Twin-Centre'],
  },
  {
    slug: 'tanzania', name: 'Tanzania & Zanzibar', region: 'Africa', priorityRank: 37,
    strapline: 'The safari, then the sea.',
    blurb: 'Serengeti migrations, Ngorongoro’s wild bowl and Zanzibar’s spice-scented beaches.',
    tags: ['Safari', 'Wildlife', 'Beach', 'Honeymoon', 'Family', 'Luxury'],
    seasonality: { best: [6, 7, 8, 9, 10, 1, 2], good: [3, 12], possible: [4, 5, 11] },
    subDestinations: [
      { heading: 'Serengeti', body: 'The great migration’s endless stage.' },
      { heading: 'Ngorongoro Crater', body: 'A collapsed volcano holding Africa’s densest wildlife.' },
      { heading: 'Zanzibar', body: 'Stone Town lanes and powder beaches on the spice island.' },
    ],
    experiences: [
      { heading: 'Migration river crossings', body: 'Wildebeest running the gauntlet (Jul–Oct, northern Serengeti).' },
      { heading: 'Crater-floor game drive', body: 'Lions, rhino and flamingos inside the caldera.' },
      { heading: 'Hot-air balloon safari', body: 'Sunrise drift over the plains, champagne on landing.' },
      { heading: 'Spice-farm & Stone Town tour', body: 'Cloves, vanilla and Freddie Mercury’s birthplace.' },
    ],
    stay: [
      { heading: 'Migration camps', body: 'Mobile tented luxury that follows the herds.' },
      { heading: 'Crater-rim lodges', body: 'Breakfast above the wild bowl.' },
      { heading: 'Zanzibar beach houses', body: 'Barefoot boutiques on Nungwi and Paje.' },
    ],
    journeyIdeas: ['Serengeti Safari & Zanzibar', 'Tanzania Family Safari', 'Great Migration Journey', 'Zanzibar Beach & Spice Island'],
  },
  {
    slug: 'kenya', name: 'Kenya', region: 'Africa', priorityRank: 38,
    strapline: 'Where safari was invented.',
    blurb: 'Masai Mara big cats, elephant orphans and a coast of dhows and coral lagoons.',
    tags: ['Safari', 'Wildlife', 'Family', 'Beach', 'Conservation', 'Luxury'],
    seasonality: { best: [7, 8, 9, 10, 1, 2], good: [6, 12, 3], possible: [4, 5, 11] },
    subDestinations: [
      { heading: 'Masai Mara', body: 'Big-cat country and the migration’s Kenyan act (Jul–Oct).' },
      { heading: 'Amboseli', body: 'Elephant herds beneath Kilimanjaro’s snow.' },
      { heading: 'Laikipia', body: 'Conservancy safaris: rhino tracking, camel treks, no crowds.' },
      { heading: 'The coast', body: 'Diani’s white sand and Lamu’s Swahili time capsule.' },
    ],
    experiences: [
      { heading: 'Mara game drives', body: 'Lion prides and river crossings with legendary guides.' },
      { heading: 'Giraffe breakfast', body: 'Nairobi’s most famous morning visitors.' },
      { heading: 'Maasai village visits', body: 'Community-led cultural exchanges done respectfully.' },
      { heading: 'Dhow sunset sails', body: 'Lamu’s ancient rhythm under lateen sails.' },
    ],
    stay: [
      { heading: 'Mara tented camps', body: 'Canvas luxury with lions in the soundtrack.' },
      { heading: 'Conservancy lodges', body: 'Exclusive traverse rights and walking safaris.' },
      { heading: 'Diani beach houses', body: 'Indian Ocean ease after the bush.' },
    ],
    journeyIdeas: ['Masai Mara & Coast', 'Kenya Family Safari', 'Laikipia & Mara Luxury Safari', 'Kenya Safari & Zanzibar'],
  },
  {
    slug: 'ireland', name: 'Ireland', region: 'Europe', priorityRank: 39,
    strapline: 'Forty shades of green, one great welcome.',
    blurb: 'Wild Atlantic cliffs, castle stays, links golf and pubs where the music finds you.',
    tags: ['Self-Drive', 'Golf', 'Countryside', 'Family', 'Culture', 'Castles'],
    seasonality: { best: [5, 6, 7, 8, 9], good: [4, 10], possible: [11, 12, 1, 2, 3] },
    subDestinations: [
      { heading: 'Dublin', body: 'Georgian squares, Trinity’s library and a pint where it’s brewed.' },
      { heading: 'The Wild Atlantic Way', body: '2,500km of cliff-edge coast from Cork to Donegal.' },
      { heading: 'Kerry & the southwest', body: 'The Ring of Kerry, Killarney’s lakes and Dingle’s dolphins.' },
    ],
    experiences: [
      { heading: 'Cliffs of Moher at golden hour', body: 'Seven hundred vertical feet of Atlantic drama.' },
      { heading: 'Trad music sessions', body: 'Fiddles in snug corners — we know which pubs.' },
      { heading: 'Links golf pilgrimages', body: 'Ballybunion, Lahinch and Portmarnock tee times.' },
      { heading: 'Castle-stay nights', body: 'Four-posters and falconry on ancestral estates.' },
    ],
    stay: [
      { heading: 'Castle hotels', body: 'Ashford and Dromoland grandeur.' },
      { heading: 'Georgian townhouses', body: 'Dublin doors with breakfast worth waking for.' },
      { heading: 'Coastal country houses', body: 'Turf fires after Atlantic walks.' },
    ],
    journeyIdeas: ['Dublin & Wild Atlantic Way', 'Ireland Family Road Trip', 'Ireland Golf Journey', 'Castles, Coast & Countryside'],
  },
  {
    slug: 'new-zealand', name: 'New Zealand', region: 'Oceania', priorityRank: 40,
    strapline: 'The world’s most beautiful road trip.',
    blurb: 'Fiords, glaciers, geothermal wonder and adventure capital energy — Middle-earth for real.',
    tags: ['Self-Drive', 'Nature', 'Adventure', 'Family', 'Luxury Lodges', 'Wine'],
    seasonality: { best: [11, 12, 1, 2, 3], good: [4, 10], possible: [5, 6, 7, 8, 9] },
    subDestinations: [
      { heading: 'Queenstown & Fiordland', body: 'Adventure capital and Milford Sound’s vertical mile.' },
      { heading: 'Rotorua & the North', body: 'Geysers, Maori culture and Hobbiton’s round doors.' },
      { heading: 'Marlborough & Hawke’s Bay', body: 'Sauvignon country and art-deco Napier.' },
    ],
    experiences: [
      { heading: 'Milford Sound cruise', body: 'Waterfalls off the bow beneath Mitre Peak.' },
      { heading: 'Hobbiton at golden hour', body: 'The Shire, ale at the Green Dragon included.' },
      { heading: 'Glacier heli-hikes', body: 'Land on Franz Josef’s ice by helicopter.' },
      { heading: 'Maori hangi nights', body: 'Earth-oven feasts and haka with mana.' },
    ],
    stay: [
      { heading: 'Luxury lodges', body: 'World-famous retreats on lakes and clifftops.' },
      { heading: 'Lakeside boutique hotels', body: 'Queenstown and Wanaka views.' },
      { heading: 'Vineyard cottages', body: 'Sleep among the sauvignon.' },
    ],
    journeyIdeas: ['New Zealand North & South Islands', 'South Island Family Adventure', 'New Zealand Luxury Lodges & Landscapes', 'New Zealand Golf & Wine Journey'],
  },
];
